### ISSUE TITLE
pcs stonith confirm <node> doesn't do any checking

### ISSUE THREAD

**Issue by blikosar** [ClusterLabs/pcs#106]
I had an accidental copy/paste and learned that pcs stonith confirm, when passed _any_ since parameter, will indicate success.  For example, I unintentionally ran "pcs stonith confirm liko@redhat.com" and it indicated success.  I believe it would be trivial to add a check to ensure that the node mentioned is a pacemaker or corosync member, but I'm unfamiliar with the code base.  I'm happy to try - I was thinking of re-using the code under stonith_level_add where it checks if what's specified is a node (currently lines 231-236 of stonith.py).  Would that be a good place to start?

**Comment by tomjelinek** [comment]
Yes, that looks all right. We just want to skip the check when called from the `quorum_unblock_cmd` function in the `quorum.py` file (in a similar manner we skip the confirmation) because in that case we already know the node exists.

Thanks for bringing this up.

**Comment by tomjelinek** [comment]
Confirming a node not present in a cluster is actually a feature not a bug. See https://bugzilla.redhat.com/show_bug.cgi?id=1386273 for more details.

**Comment by tomjelinek** [comment]
Updated stonith confirm documentation in https://github.com/ClusterLabs/pcs/commit/ebfd2a381608c39c38cd15c9b575cda06cdb6feb
