### ISSUE TITLE
when use --wait, whether the command execute successfully or not ? 

### ISSUE THREAD

**Issue by Linda679** [ClusterLabs/pcs#107]
Hi all,

When I specify --wait param in pcs command as:
# pcs resource disable xxx --wait=3
I find the command could not execute successfully, the output like this:
Error: waiting timeout
Resource 'testdomain000' is running on node workbox.
Pending actions:
	Action 9: e480NIC_monitor_10000	on workbox
	Action 8: e480NIC_start_0	on workbox
	Action 7: ClusterIP_monitor_10000	on workbox
Error performing operation: Timer expired
then, I use '# echo $?' to check, I get value 1
but when I use '#pcs resource show' to check resource, find that xxx resource had been in stopped status, seems the 'pcs resource disable' command had been worked.
From pcs resource help, it says:
disable <resource id> [--wait[=n]]
        Attempt to stop the resource if it is running and forbid the cluster
        from starting it again.  Depending on the rest of the configuration
        (constraints, options, failures, etc), the resource may remain
        started.  If --wait is specified, pcs will wait up to 'n' seconds for
        the resource to stop and then return 0 if the resource is stopped or 1
        if the resource has not stopped.  If 'n' is not specified it defaults
        to 60 minutes.
So I'm confused... If the command is unsuccessful why the resource had been stopped? If the command execute successfully why it prompts error message and why the return value is 1?

**Comment by tomjelinek** [comment]
Hi @Linda679,

The command works in two parts.  First it tells the cluster to disable specified resource.  Then it waits for the cluster to react to the change in configuration (a resource has been disabled).

It may happen it takes a little bit more than 3 seconds to stop the resource, so the waiting fails.  But the resource gets stopped right after that and that is why `pcs status` shows the resource is stopped.  If waiting fails, pcs returns 1 - because it cannot possibly know the resource will be stopped successfully just a while later.  It simply returns 1 because you wanted the change to be processed in 3 seconds and that didn't happen.

**Comment by Linda679** [comment]
Hi @tomjelinek, 
Thank you for your explain. But it sounds weird, is that mean if not just use the specified time like '3s' to stop the resource it will always return 1? no matter whether the resource is really successfully stopped or not ?

**Comment by tomjelinek** [comment]
Hi @Linda679,

If the resource stops within the specified time limit, pcs returns 0. If the resource doesn't stop within the time limit, pcs returns 1. That's the point of `--wait`. So it does matter whether the resource stopped or not. It's a little bit more complicated though. Stopping a resource may cause additional events in the cluster, depending on constraints and other cluster settings, like stopping dependent resources. `--wait` actually waits for all these related operations to finish.

If you don't care whether and when the resource actually stops, do not specify `--wait` at all. In that case pcs only disables the resource (tells pacemaker the resource should not be running), doesn't wait for the resource to stop and returns 0 on success or 1 on error.

**Comment by tomjelinek** [comment]
Closing this as the discussion seems to be over. Feel free to reopen if you have any questions.
