### ISSUE TITLE
tokens cannot be written

### ISSUE THREAD

**Issue by eileon** [ClusterLabs/pcs#110]
pcs cluster auth does not work because token are unavailable

They are unavailable because they don't exist in /var/lib/pcsd

They don't exist because they are never written. Right ? ...

(In pcs.rb write_tokens not called anywhere)

**Comment by tomjelinek** [comment]
`pcs cluster auth` works just fine when no tokens are available.

`write_tokens` function in `pcs.rb` file is most likely a trace of old code and is not needed. Tokens are written in `save_sync_new_tokens` function in `cfgsync.rb` file.

Let's move the discussion to the original issue https://github.com/ClusterLabs/pcs/issues/109.
