### ISSUE TITLE
Support for tickets

### ISSUE THREAD

**Issue by roidelapluie** [ClusterLabs/pcs#111]
Would be great to have command line support for pacemaker tickets: both creation/modification and enabling/disabling tickets

**Comment by tomjelinek** [comment]
Hi @roidelapluie,

Do you mean ticket constraints and booth tickets? Those are supported since pcs 0.9.154.

**Comment by roidelapluie** [comment]
Oh OK. I hope it will make it to rhel one day...

**Comment by tomjelinek** [comment]
Ticket constraints and Booth tickets are supported by pcs which is available in RHEL 7.3. It says it is pcs-0.9.152 but the support is there.

**Comment by roidelapluie** [comment]
Really cool. Did Booth make its way too?

**Comment by tomjelinek** [comment]
Yes, Booth is also available in RHEL 7.3.

**Comment by roidelapluie** [comment]
Thanks
