### ISSUE TITLE
pcs cluster setup --name archiclust archie archicomble --force                            is not working 

### ISSUE THREAD

**Issue by eileon** [ClusterLabs/pcs#114]
```
 [root@archie corosync]# pcs cluster setup --name archiclust archie archicomble --force
 Destroying cluster on nodes: archie, archicomble...
 archicomble: Error connecting to archicomble - (HTTP error: 400)
 archie: Error connecting to archie - (HTTP error: 400)
 archicomble: Successfully destroyed cluster
 archie: Successfully destroyed cluster

 Sending cluster config files to the nodes...
 archie: Succeeded
 archicomble: Succeeded

 Synchronizing pcsd certificates on nodes archie, archicomble...
 archicomble: Success
 archie: Success 

 Restarting pcsd on the nodes in order to reload the certificates...
 archicomble: Success
 archie: Success
```

Command is done on archie. Strangely corosync can be re-run on archicomble but corosync cannot be re-run on archie.

But command :+1: 

```
 [root@archie moulonguetn]# pcs cluster setup --name archiclust 192.168.1.2 192.168.1.3 --force
 Destroying cluster on nodes: 192.168.1.2, 192.168.1.3...
 192.168.1.2: Error connecting to 192.168.1.2 - (HTTP error: 400)
 192.168.1.3: Error connecting to 192.168.1.3 - (HTTP error: 400)
 192.168.1.2: Successfully destroyed cluster
 192.168.1.3: Successfully destroyed cluster

 Sending cluster config files to the nodes...
 192.168.1.2: Succeeded
 192.168.1.3: Succeeded

 Synchronizing pcsd certificates on nodes 192.168.1.2, 192.168.1.3...
 192.168.1.3: Success
 192.168.1.2: Success

 Restarting pcsd on the nodes in order to reload the certificates...
 192.168.1.3: Success
 192.168.1.2: Success 
```

makes corosync can be re-run on archie and on archicomble.

It's ok with ip addresses but not with nodes names.

**Comment by tomjelinek** [comment]
It's not OK in either case, see the errors right on the top of the output. I cannot really tell what went wrong though unless you provide output of the command run with `--debug` flag and content of the `/var/log/pcsd/pcsd.log` files from the nodes.

Also I cannot even guess what went wrong with corosync as I can see no error message neither `/etc/corosync/corosync.conf` from any node.

**Comment by tomjelinek** [comment]
I think the corosync issue is a duplicate to https://github.com/ClusterLabs/pcs/issues/116 and the pcs issue (HTTP 400) is a duplicate to https://github.com/ClusterLabs/pcs/issues/115#issuecomment-255112413. Therefore I'm closing this.

Feel free to reopen and provide further details if the issue hasn't been resolved for you.
