### ISSUE TITLE
pcs status gives false result

### ISSUE THREAD

**Issue by eileon** [ClusterLabs/pcs#116]
Result depends of node.

Two nodes archie and archicomble on cluster archiclust

```
[root@archie root]# pcs status
Cluster name: archiclust
Stack: corosync
Current DC: archie (version 1.1.15-92ce5ab) - partition WITHOUT quorum
Last updated: Wed Oct 26 18:18:59 2016
Last change: Wed Oct 26 17:49:13 2016 by root via cibadmin on archie

2 nodes configured
0 resources configured

Online: [ archie ]
OFFLINE: [ archicomble ]

No resources


Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled
```

archicomble seen OFFLINE from archie

```
[root@archicomble root]# pcs status
Cluster name: archiclust
Stack: corosync
Current DC: archicomble (version 1.1.15-416f98a) - partition WITHOUT quorum
Last updated: Wed Oct 26 18:26:53 2016
Last change: Wed Oct 26 18:12:57 2016 by root via cibadmin on archicomble

2 nodes configured
0 resources configured

Online: [ archicomble ]
OFFLINE: [ archie ]

No resources


Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled


```

archie seen OFFLINE from archicomble

ufw and iptables not running on both nodes

https://archie:2224 and https://archicomble:2224 show 
archie blue (pacemaker and corosync connected) and archicomble red (pacemaker and corosync Not Connected)
then one minute after
archicomble blue (pacemaker and corosync connected) and archie red (pacemaker and corosync Not Connected)
then again every minute.

Is it normal behaviour ?

**Comment by eileon** [comment]
I find out that removing
127.0.0.1      localhost.localdomain   localhost archie
and 
127.0.0.1      localhost.localdomain   localhost archicomble
in /etc/hosts erspectively of archie and archicomble
correct behaviour.
Now archie and archicomble are blue in web configuration pages and 

```
[root@archie ~]# pcs status
Cluster name: archiclust
Stack: corosync
Current DC: archicomble (version 1.1.15-416f98a) - partition with quorum
Last updated: Thu Oct 27 09:28:03 2016
Last change: Wed Oct 26 19:06:21 2016 by hacluster via crmd on archicomble

2 nodes configured
0 resources configured

Online: [ archicomble archie ]

No resources


Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled

```

```
[root@archicomble ~]# pcs status
Cluster name: archiclust
Stack: corosync
Current DC: archicomble (version 1.1.15-416f98a) - partition with quorum
Last updated: Thu Oct 27 09:26:26 2016
Last change: Wed Oct 26 19:02:51 2016 by hacluster via crmd on archie

2 nodes configured
0 resources configured

Online: [ archicomble archie ]

No resources


Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled
```
And 
::1 localhost in /etc/hosts makes corosync unable to run

So if /etc/hosts is so sensititive and does not permit locahost address with nodes address , why not to parse it somewhere and raise up an readable configuration error in case of ?

**Comment by tomjelinek** [comment]
This is not a pcs issue.

Pcs merely displays status of underlying cluster daemons. If the daemons report they don't see other nodes, then there is nothing pcs can do about it. The issue must be resolved in the daemons.

Checking /etc/hosts in pcs doesn't seem do be a viable solution for a simple reason: when should pcs check it? When running cluster setup? What if the file changes after that?

I suggest you to raise this issue in users@clusterlabs.org mailing list http://clusterlabs.org/mailman/listinfo/users
