### ISSUE TITLE
VIP problem when Pacemaker failover. 

### ISSUE THREAD

**Issue by gksasiwakoti** [ClusterLabs/pcs#117]
Hi all,

i'm using CentOS release 6.8 (Final) as a KVM and i configured 3
nodes(PM1.local,PM2.local and PM3.local), and using
CMAN clustering. Resources running at two nodes as Active node then another
one node is for Fail-over resource as a Standby node. Configured resources
are groupA and groupB, 5 resources are configured in each resource group.
groupA is Basically run at PM1.local and groupB at PM2.local. If fail any
resource group it'll fail-over at PM3.local. On PM3.local can run only one
Resource group at a time. groupA should not run at PM2.local and groupB
should not run at PM1.local. groupA or groupB resources not move back on
own nodes from PM3.local automatically, if need to move back on own nodes,
can move by manually and I setup two VIP address but when i using (ps aux | grep “corosync” | grep -v grep | awk '{ print $2 }' | xargs kill -9) command for kill corosync it’ll failover to another node but that failed node also having VIP. Normally when failed resource on one node it’ll handover VIP and all running resources to another node but have some problem with my configuration. Thanks in advance

version information:
CentOS release 6.8 (Final) (KVM)
Pacemaker 1.1.14-8.el6_8.1
Cman Version: 6.2.0

**Comment by tomjelinek** [comment]
Hi @gksasiwakoti,

This does not look like a pcs issue to me. I suggest you to continue in the thread you already started at users@clusterlabs.org mailing list: http://clusterlabs.org/pipermail/users/2016-November/004421.html

**Comment by gksasiwakoti** [comment]
@tomjelinek 
Thank you for suggestion but I don't know I'm not getting reply from users@clusterlabs.org so asking here.
