### ISSUE TITLE
Liberation font license violation

### ISSUE THREAD

**Issue by vvidic** [ClusterLabs/pcs#125]
Just got a [report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851115) that the Liberation fonts included in the pcs releases don't have a source included and therefore violate the font license:

```
pcsd/public/css/LiberationSans-BoldItalic.ttf
pcsd/public/css/LiberationSans-Italic.ttf
pcsd/public/css/LiberationSans-Regular.ttf
pcsd/public/css/LiberationSans-Bold.ttf
```

Would it be possible to have the fonts installed during package build time or installation rather than including them in the psc source directly?

**Comment by jnpkrn** [comment]
One of the historical paradoxes as back then, when I was assigned to
a project `sunzi` that was meant to be what subsequently emerged as
`pcs` from another team, I took building from source seriously from
the beginning, including this very font family:
https://git.fedorahosted.org/cgit/sunzi.git/commit/?h=development&id=81c85c9b23447fc2943c84a495864a132a213f3f

Memories aside, isn't this more a bundling issue that could be solved
easily by dropping the prebuilt fonts from the source package and
copying/linking them at the expected location from the in-system
locations depending where the native distribution-specific packages
for these fonts (assuming they exist) place them
+ adding respective dependencies?

They appear packaged in Debian:
https://packages.debian.org/jessie/fonts-liberation
(as well as many RPM-based distros including those being cared about
the most)

**Comment by vvidic** [comment]
On Thu, Jan 12, 2017 at 09:28:51AM -0800, Jan Pokorný wrote:
> Memories aside, isn't this more a bundling issue that could be solved
> easily by dropping the prebuilt fonts from the source package and
> copying/linking them at the expected location from the in-system
> locations depending where the native distribution-specific packages
> for these fonts (assuming they exist) place them
> + adding respective dependencies?
> 
> They appear packaged in Debian:
> https://packages.debian.org/jessie/fonts-liberation
> (as well as many RPM-based distros including those being cared about
> the most)

Exactly, we are going to use the ttf files from fonts-liberation.
The thing is we can't use the tar.gz releases anymore because of
the liberation ttf included there without the sources:

  https://github.com/ClusterLabs/pcs/releases

The overpass font in the same directory is fine because there are
sources next to the ttf files:

  https://github.com/ClusterLabs/pcs/tree/master/pcsd/public/css

I was hoping we could work something out if a package like
fonts-liberation exists on the RHEL side too so we can still
take your releases without repackaging to remove the liberation
ttfs.

-- 
Valentin

**Comment by tomjelinek** [comment]
I think there are actually no source files for the overpass fonts in pcs either. Also this is a bundling issue as well as noted by @jnpkrn.

Based on that I decided to remove all the bundled fonts. I updated Makefile so it finds the fonts in the system and links them to pcsd where the ttf files originally were. You need to make pcs depend on the fonts and build-depend on the fonts and fontconfig for this to work.

Patch: https://github.com/ClusterLabs/pcs/commit/a5dae2c47594e8a1fce340385bcc80c8ec09de04

**Comment by vvidic** [comment]
On Fri, Jan 13, 2017 at 08:05:10AM -0800, Tomáš Jelínek wrote:
> Based on that I decided to remove all the bundled fonts. I updated Makefile
> so it finds the fonts in the system and links them to pcsd where the ttf
> files originally were. You need to make pcs depend on the fonts and
> build-depend on the fonts and fontconfig for this to work.

Thanks for the update :)  Liberation fonts are already symlinked in
the Debian package and we'll work out something for the Overpass too.

-- 
Valentin
