### ISSUE TITLE
[cli] plain "pcs stonith enable/disable" should be alias for "pcs property set stonith-enabled=true/false"

### ISSUE THREAD

**Issue by jnpkrn** [ClusterLabs/pcs#127]
At least it was my very first thought when reading about that syntax in
the recent release announcement:
http://oss.clusterlabs.org/pipermail/users/2017-February/005103.html
and I guess I won't be the only one having this short-circuited
assumption.

**Comment by kgaillot** [comment]
That does make sense, but we're deprecating stonith-enabled in 1.1.18 and removing it in 2.0.0, so it may not be worth the trouble now. In 2.0, stonith will be considered enabled if any stonith resource has been configured OR any resource has requires=fencing (which is the default).

**Comment by tomjelinek** [comment]
Closing per previous comment.

**Comment by kgaillot** [comment]
FYI the previous comment is still the goal, but it didn't make the 1.1.18/2.0.0 time frame, so it will happen sometime in the 2.0.* series.
