### ISSUE TITLE
Question : trouble with pcs cluster start

### ISSUE THREAD

**Issue by gtyun** [ClusterLabs/pcs#128]
Hi all,
I'm trying to build postgreSQL HA cluster. My guidance is [PAF quick start for CentOS7](http://dalibo.github.io/PAF/Quick_Start-CentOS-7.html) and [PAF quick start for CentOS6](http://dalibo.github.io/PAF/Quick_Start-CentOS-6.html).

My cluster has 2 node and I found some different result with same command.

When I typed 
`pcs cluster setup --name mycluster node01 node02 --force`
 on node01, the result message was successful. 
> Sending cluster config files to the nodes...
> node01: Succeeded
> node02: Succeeded

The /etc/corosync/corosync.conf is created and copied to node02. But /etc/cluster/cluster.conf is missing.
`pcs cluster start --all`
I got an error '   Starting cman... xmlconfig cannot find /etc/cluster/cluster.conf'
I created cluster.conf manually and retry, but it does not work as ever.

In case of node2 , 
`pcs cluster setup --name mycluster node01 node02 --force`
The result is reversed, /etc/corosync/corosync.conf is missing but /etc/cluster/cluster.conf is created and copied successfully.
`pcs cluster start --all`
And I got different error message 
> node01: Error connecting to node01 - (HTTP error: 400)

I do not know if the following has any effect.
The node01's OS is fedora25 and pcs --version is 0.9.154
The node02's OS is CentOS 6.8 and pcs --version is 0.9.148

The attachment is log of 'pcs cluster setup --name mycluster node01 node02 --debug' and 'pcs cluster start --all --debug'. 
If you need any other information, please let me know. 

Thank you.

[node01_setup.txt](https://github.com/ClusterLabs/pcs/files/795862/node01_setup.txt)
[node01_start.txt](https://github.com/ClusterLabs/pcs/files/795863/node01_start.txt)
[node02_setup.txt](https://github.com/ClusterLabs/pcs/files/795870/node02_setup.txt)
[node02_start.txt](https://github.com/ClusterLabs/pcs/files/795871/node02_start.txt)

**Comment by tomjelinek** [comment]
Hi @gtyun,

The problem is you are trying to mix two different cluster implementations in one cluster. CentOS 6.8 provides CMAN stack (pacemaker running on top of CMAN + corosync 1) whereas Fedora 25 provides corosync stack (pacemaker running on top of corosync 2). These are incompatible. You need to choose one of them (corosync 2 is recommended) and install it on both nodes.

It is generally required to have the same version of OS, cluster stack and services managed by the cluster on all nodes.

**Comment by gtyun** [comment]
Thank you for your reply. I added CentOS6.8 node03 and built cluster with node02 and node03. It works properly.
