### ISSUE TITLE
 pcs cluster auth fail can't create cluster on Centos 7.3

### ISSUE THREAD

**Issue by Luxiter** [ClusterLabs/pcs#129]
Try to create a new cluster on Centos7.3 failed with this error, but the login for user hacluster is going fine

OS:CentOS Linux release 7.3.1611 (Core)
Kernel:Linux 3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
pcsd.log
pcs cluster auth 10.121.197.55 -u hacluster -p CHANGEME --force
I, [2017-03-03T14:40:45.221673 #10643]  INFO -- : Running: /usr/sbin/corosync-cmapctl totem.cluster_name
I, [2017-03-03T14:40:45.221777 #10643]  INFO -- : CIB USER: hacluster, groups:
I, [2017-03-03T14:40:45.224503 #10643]  INFO -- : Return Value: 1
W, [2017-03-03T14:40:45.224586 #10643]  WARN -- : Cannot read config 'corosync.conf' from '/etc/corosync/corosync.conf': No such file
W, [2017-03-03T14:40:45.224649 #10643]  WARN -- : Cannot read config 'corosync.conf' from '/etc/corosync/corosync.conf': No such file or directory - /etc/corosync/corosync.conf
I, [2017-03-03T14:40:45.224931 #10643]  INFO -- : Attempting login by 'hacluster'
I, [2017-03-03T14:40:45.237337 #10643]  INFO -- : Running: id -Gn hacluster
I, [2017-03-03T14:40:45.237425 #10643]  INFO -- : CIB USER: hacluster, groups:
I, [2017-03-03T14:40:45.240165 #10643]  INFO -- : Return Value: 0
I, [2017-03-03T14:40:45.240252 #10643]  INFO -- : Successful login by 'hacluster'
::ffff:10.121.197.55 - - [03/Mar/2017:14:40:45 +0100] "POST /remote/auth HTTP/1.1" 200 36 0.0197
::ffff:10.121.197.55 - - [03/Mar/2017:14:40:45 +0100] "POST /remote/auth HTTP/1.1" 200 36 0.0199
leaifapservice1 - - [03/Mar/2017:14:40:45 CET] "POST /remote/auth HTTP/1.1" 200 36
- -> /remote/auth
I, [2017-03-03T14:40:45.468509 #10643]  INFO -- : Running: /usr/sbin/corosync-cmapctl totem.cluster_name
I, [2017-03-03T14:40:45.468618 #10643]  INFO -- : CIB USER: hacluster, groups:
I, [2017-03-03T14:40:45.471282 #10643]  INFO -- : Return Value: 1
W, [2017-03-03T14:40:45.471369 #10643]  WARN -- : Cannot read config 'corosync.conf' from '/etc/corosync/corosync.conf': No such file
W, [2017-03-03T14:40:45.471451 #10643]  WARN -- : Cannot read config 'corosync.conf' from '/etc/corosync/corosync.conf': No such file or directory - /etc/corosync/corosync.conf
I, [2017-03-03T14:40:45.471762 #10643]  INFO -- : Attempting login by 'hacluster'
I, [2017-03-03T14:40:45.485154 #10643]  INFO -- : Running: id -Gn hacluster
I, [2017-03-03T14:40:45.485223 #10643]  INFO -- : CIB USER: hacluster, groups:
I, [2017-03-03T14:40:45.487824 #10643]  INFO -- : Return Value: 0
I, [2017-03-03T14:40:45.487904 #10643]  INFO -- : Successful login by 'hacluster'
I, [2017-03-03T14:40:45.535500 #10643]  INFO -- : Running: /usr/sbin/corosync-cmapctl totem.cluster_name
I, [2017-03-03T14:40:45.535602 #10643]  INFO -- : CIB USER: hacluster, groups:
I, [2017-03-03T14:40:45.538370 #10643]  INFO -- : Return Value: 1
W, [2017-03-03T14:40:45.538453 #10643]  WARN -- : Cannot read config 'corosync.conf' from '/etc/corosync/corosync.conf': No such file
W, [2017-03-03T14:40:45.538518 #10643]  WARN -- : Cannot read config 'corosync.conf' from '/etc/corosync/corosync.conf': No such file or directory - /etc/corosync/corosync.conf
I, [2017-03-03T14:40:45.538761 #10643]  INFO -- : Attempting login by 'hacluster'
I, [2017-03-03T14:40:45.550377 #10643]  INFO -- : Running: id -Gn hacluster
I, [2017-03-03T14:40:45.550447 #10643]  INFO -- : CIB USER: hacluster, groups:
I, [2017-03-03T14:40:45.552981 #10643]  INFO -- : Return Value: 0
I, [2017-03-03T14:40:45.553059 #10643]  INFO -- : Successful login by 'hacluster'
::ffff:10.121.197.55 - - [03/Mar/2017:14:40:45 +0100] "POST /remote/auth HTTP/1.1" 200 36 0.0186
::ffff:10.121.197.55 - - [03/Mar/2017:14:40:45 +0100] "POST /remote/auth HTTP/1.1" 200 36 0.0187
leaifapservice1 - - [03/Mar/2017:14:40:45 CET] "POST /remote/auth HTTP/1.1" 200 36
- -> /remote/auth
I, [2017-03-03T14:40:45.594497 #10643]  INFO -- : Running: /usr/sbin/pcs status nodes corosync
I, [2017-03-03T14:40:45.594599 #10643]  INFO -- : CIB USER: hacluster, groups:
I, [2017-03-03T14:40:45.742047 #10643]  INFO -- : Return Value: 1
I, [2017-03-03T14:40:45.742495 #10643]  INFO -- : Saved config 'tokens' version 10 37ade24eef3f1b4b6b31918bcf519f2fd16a5d14 to '/var/lib/pcsd/tokens'
::ffff:10.121.197.55 - - [03/Mar/2017:14:40:45 +0100] "POST /remote/auth HTTP/1.1" 200 36 0.2748
::ffff:10.121.197.55 - - [03/Mar/2017:14:40:45 +0100] "POST /remote/auth HTTP/1.1" 200 36 0.2749
leaifapservice1 - - [03/Mar/2017:14:40:45 CET] "POST /remote/auth HTTP/1.1" 200 36
- -> /remote/auth
Error: Unable to communicate with pcsd

**Comment by Luxiter** [comment]
pcs cluster auth leaifapservice1 leaifapservice2 -u hacluster -p CHANGEME --force --debug

Running: /usr/bin/ruby -I/usr/lib/pcsd/ /usr/lib/pcsd/pcsd-cli.rb auth
--Debug Input Start--
{"username": "hacluster", "local": false, "nodes": ["leaifapservice1", "leaifapservice2"], "password": "CHANGEME", "force": true}
--Debug Input End--
Return Value: 0
--Debug Output Start--
/usr/lib/pcsd/bootstrap.rb:58: warning: Insecure world writable dir /usr/local/nvm in PATH, mode 040777
{
  "status": "ok",
  "data": {
    "auth_responses": {
      "leaifapservice1": {
        "status": "ok",
        "token": "77ecf6de-7b83-44b2-a220-cb65c2a590fc"
      },
      "leaifapservice2": {
        "status": "ok",
        "token": "11f29c39-de22-4f00-9127-478f75f84838"
      }
    },
    "sync_successful": true,
    "sync_nodes_err": [

    ],
    "sync_responses": {
    }
  },
  "log": [
    "I, [2017-03-03T15:48:54.418120 #7075]  INFO -- : PCSD Debugging enabled\n",
    "D, [2017-03-03T15:48:54.418190 #7075] DEBUG -- : Did not detect RHEL 6\n",
    "I, [2017-03-03T15:48:54.418228 #7075]  INFO -- : Running: /usr/sbin/corosync-cmapctl totem.cluster_name\n",
    "I, [2017-03-03T15:48:54.418254 #7075]  INFO -- : CIB USER: hacluster, groups: \n",
    "D, [2017-03-03T15:48:54.420510 #7075] DEBUG -- : []\n",
    "D, [2017-03-03T15:48:54.420558 #7075] DEBUG -- : [\"Failed to initialize the cmap API. Error CS_ERR_LIBRARY\\n\"]\n",
    "D, [2017-03-03T15:48:54.420611 #7075] DEBUG -- : Duration: 0.002235266s\n",
    "I, [2017-03-03T15:48:54.420670 #7075]  INFO -- : Return Value: 1\n",
    "W, [2017-03-03T15:48:54.420721 #7075]  WARN -- : Cannot read config 'corosync.conf' from '/etc/corosync/corosync.conf': No such file\n",
    "W, [2017-03-03T15:48:54.420773 #7075]  WARN -- : Cannot read config 'corosync.conf' from '/etc/corosync/corosync.conf': No such file or directory - /etc/corosync/corosync.conf\n",
    "I, [2017-03-03T15:48:54.536411 #7075]  INFO -- : Running: /usr/sbin/pcs status nodes corosync\n",
    "I, [2017-03-03T15:48:54.536469 #7075]  INFO -- : CIB USER: hacluster, groups: \n",
    "D, [2017-03-03T15:48:54.679350 #7075] DEBUG -- : []\n",
    "D, [2017-03-03T15:48:54.679448 #7075] DEBUG -- : [\"Error: Unable to read /etc/corosync/corosync.conf: No such file or directory\\n\"]\n",
    "D, [2017-03-03T15:48:54.679492 #7075] DEBUG -- : Duration: 0.142849612s\n",
    "I, [2017-03-03T15:48:54.679566 #7075]  INFO -- : Return Value: 1\n",
    "I, [2017-03-03T15:48:54.680147 #7075]  INFO -- : Saved config 'tokens' version 17 a675e9b74f9a99f4c58a2c7ff7d4d916237a6179 to '/var/lib/pcsd/tokens'\n"
  ]
}
--Debug Output End--

Error: Unable to communicate with pcsd

**Comment by tomjelinek** [comment]
This has already been reported and fixed. See https://github.com/ClusterLabs/pcs/issues/124 for more details.
