### ISSUE TITLE
pcsd tokens not created 

### ISSUE THREAD

**Issue by Vclinton** [ClusterLabs/pcs#131]
I'm attempting to deploy pcs/corosync into a diskless environment and I'm having issues with getting the successful creation of the "/var/lib/pcsd/tokens" file.  I'm new at the pcs/corosync deployment and I'm not sure what information you'll require to provide me with assistance.  I'm setting this up to work with a 6 node cluster at LANL in support of a diskless HA solution with Lustre.

**Comment by tomjelinek** [comment]
Describing the issues you have would be a great start. However I'm afraid pcsd hasn't been designed for nor tested with diskless machines.
Besides that, where and how do you plan to store other cluster configuration files like `corosync.conf`, `/var/lib/pacemaker` directory and so on?
