### ISSUE TITLE
pcs resource create does not propagate agent's default actions if it doesn't know about them

### ISSUE THREAD

**Issue by dciabrin** [ClusterLabs/pcs#132]
I want to add specific actions in a resource agent and dedicate each action to a special part of my overall resource monitoring. 
The schema in pacemaker imposes no special restriction as to what the action name could be, i.e. I could define in the meta-data of my resource agent:

```
<actions>
<action name="monitor" role="Master" depth="0" timeout="30" interval="10" />
<action name="monitor" role="Slave" depth="0" timeout="30" interval="30" />
<action name="**sync-monitor**" role="Slave" depth="0" timeout="30" interval="8" on-fail="block"/>
...
</actions>
```

Pacemaker would call the resource agent every 8s while in Slave state, ans pass operation name "sync-monitor" as a parameter. Such splitting improves readibility and maitenance of the resource agent.

However, when using pcs to create the resource, pcs only considers the advertised default actions if they have "known" names such as start, stop, monitor, promote and demote (https://github.com/ClusterLabs/pcs/blob/master/pcs/lib/resource_agent.py#L24).

As such, there's currently a discrepancy between what pcs permits and what pacemaker allows.

**Comment by idevat** [comment]
Pcs allows you to put any action but you must specify it explicitly:
`pcs resource create R your:resource-agent op sync-monitor interval=8`
Pcs puts only the default operation into the CIB implicitly.

**Comment by dciabrin** [comment]
@idevat, correct but then that is no longer transparent for the client (in my case tripleo OpenStack installer): I would need to change the way I call pcs for that resource, and I don't want that implementation detail to go up to the client layer.

I agree that my issue looks more like an "unexpected behaviour"  than a pure "discrepancy" between pcs and pacemaker. So question is: pcs seems to copy only known default operations on purpose, but is this the behaviour that we want?

**Comment by tomjelinek** [comment]
Fixed in https://github.com/ClusterLabs/pcs/commit/7980215694e81c7fa33a6c789293507334b24a46. Thanks for pointing this out.
