### ISSUE TITLE
make install in suse12 sp2 Makefile:85: recipe for target 'install' failed

### ISSUE THREAD

**Issue by kuncao** [ClusterLabs/pcs#140]
hello experts
I down pcs-0.9.155.tar.gz
after tar -zxvf pcs-0.9.155.tar.gz  error occur when install the pcs

/home/pcs # make install
python setup.py install --root=/ 
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup, Command, find_packages
ImportError: No module named setuptools
Makefile:85: recipe for target 'install' failed
make: *** [install] Error 1
/home/pcs # python setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup, Command, find_packages
ImportError: No module named setuptools
please help me to resolve the issue
thanks a lot

**Comment by kuncao** [comment]
install pip

https://pip.pypa.io/en/stable/installing/

download get-pip.py
Installing with get-pip.py
To install pip, securely download get-pip.py.
https://bootstrap.pypa.io/get-pip.py
 pip install -U pip setuptools
Requirement already up-to-date: pip in /usr/lib/python2.7/site-packages
Requirement already up-to-date: setuptools in /usr/lib/python2.7/site-packages
then install pcs

**Comment by tomjelinek** [comment]
readme now lists dependencies: https://github.com/ClusterLabs/pcs/commit/1f878c946c1ab52714f9289c41f2203e72c3b207
