### ISSUE TITLE
pcs cluster setup with HTTP 400 error.

### ISSUE THREAD

**Issue by magic4u** [ClusterLabs/pcs#142]
CentosOS 6.9
pcs: pcs-0.9.155-2.el6
corosync: corosync-1.4.7-5.el6.x86_64
pacemaker: pacemaker-1.1.15-5.el6.x86_64

-----------------------------------------
pcs cluster setup --name cluster 101.1.11.1 --start --enable --force --debug
----------------------------------------
The debug log:

101.1.11.1: Stopping Cluster (pacemaker)...
Running: /usr/bin/ruby -I/usr/lib/pcsd/ /usr/lib/pcsd/pcsd-cli.rb read_tokens
--Debug Input Start--
{}
--Debug Input End--
Return Value: 0
--Debug Output Start--
{
  "status": "ok",
  "data": {
    "101.1.11.3": "8ff4e730-e2d3-4cfc-bd37-12e7d931a3a4",
    "101.1.11.2": "5a48200b-d3da-4920-aa5d-8346c12d6a59",
    "101.1.11.1": "9e8b7f2a-6fb3-4964-a056-c62ea2adf367"
  },
  "log": [
    "I, [2017-07-27T15:55:50.315862 #5625]  INFO -- : PCSD Debugging enabled\n",
    "D, [2017-07-27T15:55:50.315980 #5625] DEBUG -- : Detected RHEL 6\n",
    "I, [2017-07-27T15:55:50.316056 #5625]  INFO -- : Running: /usr/sbin/corosync-objctl cluster\n",
    "I, [2017-07-27T15:55:50.316122 #5625]  INFO -- : CIB USER: hacluster, groups: \n",
    "D, [2017-07-27T15:55:50.320025 #5625] DEBUG -- : []\n",
    "D, [2017-07-27T15:55:50.320131 #5625] DEBUG -- : [\"Failed to initialize the objdb API. Error 6\\n\"]\n",
    "D, [2017-07-27T15:55:50.320229 #5625] DEBUG -- : Duration: 0.003908s\n",
    "I, [2017-07-27T15:55:50.320378 #5625]  INFO -- : Return Value: 1\n"
  ]
}
--Debug Output End--

Sending HTTP Request to: https://101.1.11.1:2224/remote/cluster_destroy
Data: None
Response Code: 400
--Debug Response Start--
Error destroying cluster:
Shutting down pacemaker/corosync services...

Traceback (most recent call last):
  File "/usr/sbin/pcs", line 9, in <module>
    load_entry_point('pcs==0.9.155', 'console_scripts', 'pcs')()
  File "/usr/lib/python2.6/site-packages/pcs/app.py", line 220, in main
    cmd_map[command](argv)
  File "/usr/lib/python2.6/site-packages/pcs/cluster.py", line 142, in cluster_cmd
    cluster_destroy(argv)
  File "/usr/lib/python2.6/site-packages/pcs/cluster.py", line 1885, in cluster_destroy
    utils.stop_service(service)
  File "/usr/lib/python2.6/site-packages/pcs/utils.py", line 2206, in stop_service
    stdout, stderr, retval = cmd_runner().run([_service, service, "stop"])
  File "/usr/lib/python2.6/site-packages/pcs/lib/external.py", line 430, in run
    out_err=out_err
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 45: ordinal not in range(128)

1
--Debug Response End--
101.1.11.1: Error connecting to 101.1.11.1 - (HTTP error: 400)
Error: unable to destroy cluster
101.1.11.1: Error connecting to 101.1.11.1 - (HTTP error: 400)

**Comment by magic4u** [comment]
it caused by the system locale. when I change the locale to en_US, the command executed perfect.

**Comment by tomjelinek** [comment]
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 45: ordinal not in range(128)
```
This has been fixed in https://github.com/ClusterLabs/pcs/commit/52ea51c0006e585345199e4a3b3a8565e741d024
