### ISSUE TITLE
IPAddr2 resource on two interfaces with different names

### ISSUE THREAD

**Issue by void-in** [ClusterLabs/pcs#144]
First of all many thanks for the wonderful tool. I searched the forums but my limited knowledge of google searching is failing me. We have two Apache reverse proxies with two interfaces in each: internal and external. On the one server the interfaces are named en0 and en1 while on the other machine the interfaces are eth0 and eth1. We want to assign two floating IP addresses: one to the external interface while one to the internal. In case any of the floating IP is down, it should be transferred to the other machine. The problem is that the interface names in both machines are different. Is it possible to create a virtual resource like:
```
pcs resource create ClusterIP ocf:heartbeat:IPaddr2 ip=floating-ip-for-external cidr_netmask=32 nic=en0  op monitor interval=30s
pcs resource create ClusterIP ocf:heartbeat:IPaddr2 ip=floating-ip-for-internal cidr_netmask=32 nic=en1  op monitor interval=30s
```
There is no en0 or en1 interface on the other machine (it has eth0 and eth1 as mentioned above). Any help would be really appreciated.

**Comment by tomjelinek** [comment]
Just do not specify the `nic` option at all. The IPaddr2 resource agent will then figure out what interface should be used based on the node's routing table. You may take a look at `/usr/lib/ocf/lib/heartbeat/findif.sh` to see how that works. It may be needed to set a shorter `cidr_netmask` or omit it and let it be figured out by the agent as well.

**Comment by void-in** [comment]
@tomjelinek Thank you very much for the response. That is great that the agent is figuring out the interface on its own. Will implement your solution then. I will close this issue. Thanks once again.
