### ISSUE TITLE
pcs acl "Please authenticate yourself to the local pcsd"

### ISSUE THREAD

**Issue by tuxick** [ClusterLabs/pcs#165]
After creating read-only (or any) acl for user, i kept getting "Please authenticate yourself to the local pcsd".
Checking util.py i see that although the function is "def call_local_pcsd(argv, interactive_auth=False, std_in=None)", it gets called everywhere with hardcoded "True".  Passing "False" to the calls makes pcs work as expected.

**Comment by tomjelinek** [comment]
There should not be any connection between ACLs and the "Please authenticate yourself to the local pcsd" message. What pcs commands are giving you the message? What pcs version are you using?

**Comment by tomjelinek** [comment]
Closed for inactivity. Feel free to reopen if you have any updates.
