### ISSUE TITLE
how to install pcs to custom path

### ISSUE THREAD

**Issue by s3v3ran** [ClusterLabs/pcs#167]
As there is no ./configure phase before installing, I did't find any way to inistall pcs to a custom location. It puts the binaries in /usr, configuration to /etc, etc. I need it all in one folder (/opt/linux-ha/pcs). How to achieve this?

**Comment by tomjelinek** [comment]
Have you tried `make install DESTDIR=/opt/linux-ha/pcs` and `make install_pcsd DESTDIR=/opt/linux-ha/pcs`?

**Comment by s3v3ran** [comment]
Thanks for the hit, this works. I just got another problem. When I tar the folder /opt/linux-ha/pcs and untar it on another server in the same location, assuming I set the PATH, after running "pcs status" I got this error:

Traceback (most recent call last):
  File "/opt/linux-ha/pcs/usr/sbin/pcs", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pcs==0.9.163' distribution was not found and is required by the application

Someone knows what it means? I have installed all the dependent libraries, ruby and python from distribution. Only the Corosync, Pacemaker and PCS is compiled.

**Comment by s3v3ran** [comment]
I was trying something and got a little further. The solution of the previous error is the following:
1 - creating these two links:
# ls -l /opt/linux-ha/pcs/usr/lib/python3/dist-packages
lrwxrwxrwx  1 root root     52 Apr 25 14:08 pcs -> /opt/linux-ha/pcs/usr/lib/python3/dist-packages/pcs//
lrwxrwxrwx  1 root root     69 Apr 26 16:37 pcs-0.9.163.egg-info -> /opt/linux-ha/pcs/usr/lib/python3/dist-packages/pcs-0.9.163.egg-info//

2 - installing following packages:
# apt install python3-lxml python3-pycurl

Now I got another error which is not anymore connected with PCS (it's the problem with the custom location of Corosync binaries) so i close this issue.

**Comment by tomjelinek** [comment]
If you installed Corosync and Pacemaker to custom locations, you need to update paths in `pcs/settings_default.py` (or `psc/settings.py`) and `pcsd/settings.rb` files to reflect that. There are also pcs paths there you should update as well.

**Comment by s3v3ran** [comment]
Thanks, you are right. Changing the paths in these files helped.
