### ISSUE TITLE
PAF with Ubuntu 16.04

### ISSUE THREAD

**Issue by elwood218** [ClusterLabs/pcs#169]
Hi,

I tried to find out why the postgresql cannot start.

```
pcs resource show
 Master/Slave Set: pgsql-ha [pgsqld]
     pgsqld	(ocf::heartbeat:pgsqlms):      FAILED pgdb01
     pgsqld	(ocf::heartbeat:pgsqlms):      FAILED pgdb02
 pgsql-master-ip	(ocf::heartbeat:IPaddr2):	Stopped
```

```
pcs resource debug-start pgsqld
Error performing operation: Input/output error
Operation start for pgsqld:0 (ocf:heartbeat:pgsqlms) returned 5
 >  stderr: Use of uninitialized value $OCF_Functions::ARG[0] in pattern match (m//) at /usr/lib/ocf/resource.d/heartbeat/../../lib/heartbeat/OCF_Functions.pm line 392.
 >  stderr: ocf-exit-reason:PAF v2.2.0 is compatible with Pacemaker 1.1.13 and greater
```

Can someone help me with that error message?

**Comment by tomjelinek** [comment]
Hi,

This is an issue with the `ocf::heartbeat:pgsqlms` resource agent, which is out of the scope of pcs. I recommend you to contact its developer or ask the question at [ClusterLabs users mailinglist](https://oss.clusterlabs.org/mailman/listinfo/users).

Based on the error message it looks like the version of `ocf::heartbeat:pgsqlms` you are using requires Pacemaker 1.1.13 or newer. Does your system fulfill that?

**Comment by tomjelinek** [comment]
Ah, OK. This seems to be actually covered at [PAF Quick Start](https://clusterlabs.github.io/PAF/Quick_Start-Debian-9-crm.html#cluster-resources). There's been a similar issue recently discussed at https://lists.clusterlabs.org/pipermail/users/2018-April/014797.html.

The error messages in `pcs resource debug-start` are provided by the PAF agent, pcs just prints them. You could file a bug against PAF to provide a better error message.
