### ISSUE TITLE
pcs stonith create problem

### ISSUE THREAD

**Issue by elwood218** [ClusterLabs/pcs#170]
Maybe this is Ansible related.. but I don't see what the hell is the problem.. :)
I hope someone else faced this problem.
Very often the statement returns ok when creating the stonith resource but it is not found in file. And I don't see that another file is created on another server or another directory - so how can that be? Does somebody have an idea? Maybe this is known to pcs ?!

I added a `grep fence_vm_foo` to check if it is in that file and even that returned true - so there must be another file where this is created..

```
TASK [paf : debug] *******************************************************************************************************************
ok: [pgdb04] => {
    "command_result": {
        "attempts": 1,
        "changed": true,
        "cmd": "pcs -f cluster_pgsql stonith create fence_vm_pgdb04 fence_vmware_soap pcmk_host_check=\"static-list\" pcmk_host_list=\"pgdb04\" port=\"pgdb04-vm\" action=\"off\" ssl=1 ssl_insecure=1 ipaddr=vcenter login=pgsql@vsphere.local passwd=foobar && grep -q fence_vm_pgdb04 cluster_pgsql",
        "delta": "0:00:00.670503",
        "end": "2018-04-26 14:24:33.151049",
        "failed": false,
        "failed_when_result": false,
        "rc": 0,
        "start": "2018-04-26 14:24:32.480546",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "",
        "stdout_lines": []
    }
}
ok: [pgdb05] => {
    "command_result": {
        "attempts": 1,
        "changed": true,
        "cmd": "pcs -f cluster_pgsql stonith create fence_vm_pgdb05 fence_vmware_soap pcmk_host_check=\"static-list\" pcmk_host_list=\"pgdb05\" port=\"pgdb05-vm\" action=\"off\" ssl=1 ssl_insecure=1 ipaddr=vcenter login=pgsql@vsphere.local passwd=foobar && grep -q fence_vm_pgdb05 cluster_pgsql",
        "delta": "0:00:00.634815",
        "end": "2018-04-26 14:24:33.109858",
        "failed": false,
        "failed_when_result": false,
        "rc": 0,
        "start": "2018-04-26 14:24:32.475043",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "",
        "stdout_lines": []
    }
}

TASK [paf : Create contraint for stonith resource] ***********************************************************************************
changed: [pgdb04 -> pgdb04]
fatal: [pgdb05 -> pgdb04]: FAILED! => {"changed": true, "cmd": ["pcs", "-f", "cluster_pgsql", "constraint", "location", "fence_vm_pgdb05", "avoids", "pgdb05=INFINITY"], "delta": "0:00:00.099251", "end": "2018-04-26 14:24:35.668476", "msg": "non-zero return code", "rc": 1, "start": "2018-04-26 14:24:35.569225", "stderr": "Error: Resource 'fence_vm_pgdb05' does not exist", "stderr_lines": ["Error: Resource 'fence_vm_pgdb05' does not exist"], "stdout": "", "stdout_lines": []}
```

**Comment by tomjelinek** [comment]
Is it possible those two `pcs stonith create` commands run in parallel? If so, then based on your pcs version, one may overwrite the result of the other. We are working on fixing CIB handling pcs commands to make them able to run in parallel, see [rhbz#1404233](https://bugzilla.redhat.com/show_bug.cgi?id=1404233) and [rhbz#1441673](https://bugzilla.redhat.com/show_bug.cgi?id=1441673) for details. Even with those fixes it is not recommended to run pcs in parallel as the approach used for CIB editing cannot be used for editing other config files (like corosync, booth, sbd) and then this kind of race condition may happen.

**Comment by elwood218** [comment]
Till now I couldn't really solve that problem.
If I find something in future I will let you know but for now I will close this ticket.
