### ISSUE TITLE
pcs cluster setup command fails with "unable to authenticate to node" though authourization succeeds

### ISSUE THREAD

**Issue by k2ganapa** [ClusterLabs/pcs#184]
PCS cluster setup issue

With below pcs and pacemaker versions, the pcs cluster auth succeeds but the cluster setup fails due to "unable to authenticate to node".

# rpm -qa | egrep "pcs|pacemaker"
pacemaker-libs-1.1.18-11.el7_5.3.x86_64
pacemaker-cli-1.1.18-11.el7_5.3.x86_64
pacemaker-1.1.18-11.el7_5.3.x86_64
pcs-0.9.162-5.el7.centos.1.x86_64
pacemaker-cluster-libs-1.1.18-11.el7_5.3.x86_64

centos.repo:
[centos-base]
name=centos repository in Lab
baseurl=http://centos.mirror.iweb.ca/7/os/x86_64/
enabled=1
protect=0
gpgcheck=0
[centos-upgrade]
name=centos repository in Lab
baseurl=http://centos.mirror.iweb.ca/7/updates/x86_64/
enabled=1
protect=0
gpgcheck=0

Steps followed:
1) With above repo file, installed pcs fence-agents-all.
yum install pcs fence-agents-all
2) Created the HA user with "passwd hacluster" on both nodes with same password.
3) Started and enabled pcsd service on both nodes.
systemctl start pcsd.service;systemctl enable pcsd.service
4) Authenticated both nodes using
pcs cluster auth hostname1 hostname2 -u hacluster -p hacluster1
5) Try doing pcs cluster setup using
pcs cluster setup --name cluster_pgsql hostname1 hostname2

Expected: To created the pcs cluster setup successfully.
Actual: The pcs cluster setup failed due to "unable to authenticate to node"

This is because "/etc/corosync/corosync.conf" file did not get created.

Please find the attachment for the complete debug logs (pcs-cluster-setup-issue.pdf)

Work around:
============
1) Login to PCS web interface: http://host-ipaddress:2224
2) Provide the username and password. In our case (hacluster/hacluster1).
3) Click the "Create New" button and provide cluster name and the hostname of the nodes associated in cluster setup.
4) Click "Create Cluster". Provide password for both the nodes on the next prompt and submit.
5) This will successfully create the cluster and corosync.conf file is also generated successfully.
6) Run the pcs cluster status on node and found to be cluster setup is up and online.
[pcs-cluster-setup-issue.pdf](https://github.com/ClusterLabs/pcs/files/2404739/pcs-cluster-setup-issue.pdf)

**Comment by tomjelinek** [comment]
This has been fixed in pcs-0.9.165 by https://github.com/ClusterLabs/pcs/commit/30b59f3b4b7f9ed3af9010163c2715aaffb0a1de. As a workaround do not use uppercase characters in your nodes' names. The problem has nothing to do with missing corosync.conf.
