### ISSUE TITLE
sudo crm_mon -Afr output issue

### ISSUE THREAD

**Issue by alexeyshishkin01** [ClusterLabs/pcs#185]
pls. see attached screen
![cp](https://user-images.githubusercontent.com/28735514/46153922-b993bb00-c27c-11e8-9ecd-1d4bb6be2a33.jpg)

**Comment by tomjelinek** [comment]
If you are really running `sudo crm_mon -Afr` then pcs is not involved in that in any way. Please, file this issue as a Pacemaker bug in its bugzilla at https://bugs.clusterlabs.org/.
