### ISSUE TITLE
100% cpu usage

### ISSUE THREAD

**Issue by kubikrobert** [ClusterLabs/pcs#186]
Hi,
for some time, I'm observing that PCS is topping the CPU (both threads - 2vCores):

I have two processes like:
`/usr/bin/ruby -C/var/lib/pcsd -I/usr/share/pcsd -- /usr/share/pcsd/ssl.rb & > /dev/null &`

Strace for both shows:

```
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
```
any ideas?

Restart always helps. But something is wrong with that for sure.

**Comment by tomjelinek** [comment]
Hi,
Similar issue has been reported in users@clusterlabs.org mailing list in May. It has been eventually tracked down as a fork bug in Ruby by Debian maintainers of pcs, see https://lists.clusterlabs.org/pipermail/users/2018-July/015418.html . Try updating your Ruby packages.
