### ISSUE TITLE
cant enable pcs cluster 

### ISSUE THREAD

**Issue by aqibsg** [ClusterLabs/pcs#189]
when I ran the following command after setting and starting the pcs cluster:
`pcs cluster enable --all`

I got the following error: 
**10.0.1.206: {"error":"true"}**

**Comment by aqibsg** [comment]
while running in debug mode:
**Sending HTTP Request to: https://10.0.1.206:2224/remote/cluster_enable
Data: None
10.0.1.206: {"error":"true"}
Response Code: 200**
--Debug Response Start--
{"error":"true"}
--Debug Response End--
Communication debug info for calling: https://10.0.1.206:2224/remote/cluster_enable
--Debug Communication Output Start--
*   Trying 10.0.1.206...
* Connected to 10.0.1.206 (10.0.1.206) port 2224 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: ip-10-0-1-206.ap-northeast-1.compute.internal (does not match '10.0.1.206')
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=MN,L=Minneapolis,O=pcsd,OU=pcsd,CN=ip-10-0-1-206.ap-northeast-1.compute.internal
* 	 start date: Mon, 14 Jan 2019 11:03:43 GMT
* 	 expire date: Thu, 11 Jan 2029 11:03:43 GMT
* 	 issuer: C=US,ST=MN,L=Minneapolis,O=pcsd,OU=pcsd,CN=ip-10-0-1-206.ap-northeast-1.compute.internal
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> GET /remote/cluster_enable HTTP/1.1
Host: 10.0.1.206:2224
User-Agent: PycURL/7.43.0 libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Accept: */*
Cookie: token=514e8dfd-b149-45c4-851c-085733c82bea

< HTTP/1.1 200 OK 
< Content-Type: text/html;charset=utf-8
< Content-Length: 16
< X-Xss-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Server: WEBrick/1.3.1 (Ruby/2.3.1/2016-04-26) OpenSSL/1.0.2g
< Date: Mon, 14 Jan 2019 11:19:03 GMT
< Connection: Keep-Alive
< 
<< {"error":"true"}
* Connection #0 to host 10.0.1.206 left intact

--Debug Communication Output End--

**Comment by tomjelinek** [comment]
Can you run `pcs cluster enable --debug` on the 10.0.1.206 node and post the output?

**Comment by aqibsg** [comment]
@tomjelinek the above post is the output I received in debug mode for enabling the cluster

**Comment by tomjelinek** [comment]
@aqibsg That does not look like the output of `pcs cluster enable --debug` to me. It looks like it is an output of `pcs cluster enable --all --debug`. Those two variants of the enable command work very differently and have very different output. The `--all` variant does not provide enough information for us to see what went wrong. Please, run `pcs cluster enable --debug` as root user on 10.0.1.206 node and post its output.

**Comment by aqibsg** [comment]
Running: /usr/sbin/corosync -v
Environment:
  HOME=/root
  HOSTNAME=d585626e3af3
  LC_ALL=C
  LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
  OLDPWD=/aqib
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  PWD=/aqib/pcs
  SHLVL=1
  TERM=xterm
  _=/usr/sbin/pcs

Finished running: /usr/sbin/corosync -v
Return value: 0
--Debug Stdout Start--
Corosync Cluster Engine, version '2.3.5'
Copyright (c) 2006-2009 Red Hat, Inc.

--Debug Stdout End--
--Debug Stderr Start--

--Debug Stderr End--

Running: /sbin/chkconfig corosync on
Environment:
  HOME=/root
  HOSTNAME=d585626e3af3
  LC_ALL=C
  LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
  OLDPWD=/aqib
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  PWD=/aqib/pcs
  SHLVL=1
  TERM=xterm
  _=/usr/sbin/pcs

**Error: unable to run command /sbin/chkconfig corosync on: No such file or directory: '/sbin/chkconfig'**

**Comment by tomjelinek** [comment]
OK, now I see what the problem is. It looks like you are not running systemd and your system is missing chkconfig binary. Upstream pcs is not ready for that situation. It works fine when systemd is used as an init system. Otherwise it only works with systems providing chkconfig, such as CentOS or RHEL. If you are running Debian, use packages provided by your distribution as they contain patches to fix this.

By the way, I can see you are running corosync 2. Be aware that corosync 2 is not supported in pcs-0.10. If you want to keep using corosync 2, switch to pcs-0.9. See [README.md](https://github.com/ClusterLabs/pcs#pcs-versions) for more info.
