### ISSUE TITLE
systemd timer feature

### ISSUE THREAD

**Issue by dream91** [ClusterLabs/pcs#193]
How can I add systemd timer resource?
By default it is adding systemd service.

If it isn't possible then I think it will be great feature :)

**Comment by tomjelinek** [comment]
This is actually a feature of pacemaker, not pcs. See https://github.com/ClusterLabs/pacemaker/pull/1508 for more info about the pacemaker part.

`pcs resource list .timer` gives a list of systemd timers available. If you do not see any, then you probably have not new enough version of pacemaker. You can create resources from them in the usual way, for example `pcs resource create test_timer systemd:dnf-makecache.timer`. 

You need pcs-0.9.155 or newer for this to work.

**Comment by souedda** [comment]
Hi dream91,
You can use RA systemd-timer of devgateway (that's work fine). 🥇 
https://github.com/devgateway/pacemaker-ra-systemd-timer

deploy it, 
or manually :
- copy on each node systemd-timer.sh to /usr/lib/ocf/resource.d/heartbeat/systemd-timer
- include content of metadata.xml in timer_meta_data() of systemd-timer RA 
use it:
pcs resource create test_timer ocf:heartbeat:systemd-timer name=test.timer
