### ISSUE TITLE
failover with "pcs node standby" kills the standby host's pcsd

### ISSUE THREAD

**Issue by computer045** [ClusterLabs/pcs#197]
## Environment
- **OS:** Ubuntu 18.04.2 server
- **Pacemaker version:** 1.1.18
- **Corosync version:** 2.4.3
- **pcs version:** 0.9.164

### Description

I have 2 servers running in cluster (**server1**, **server2**). One server at a time runs with all the resources. The exception is for 2 resources that are configured as clones.

When I try to do a failover from **server1** to **server2** with the `pcs node standby` command, **server1**'s `pcsd` service crashes. **server1** is marked as *UNCLEAN* and offline. The services are in error state on **server2** for a little bit before starting the ressources. I have to restart pacemaker on **server1** with `pcs cluster start`, for it to rejoin the cluster.

If I do the *standby* operation on the `pcsd` web ui, ~~the failover works flawlessly~~ the same thing happens, but not always.

I looked at the code and other issues and I did not find anything related to my problem.

If you need more information, I'll do my best to provide it.

**Comment by computer045** [comment]
This is the output of the failure using `journalctl -xe`:

```log
Mar 08 15:53:20 server2 Filesystem(net-home-bind)[42866]: INFO: sending signal TERM to: root      3035     1  0 Mar07 ?        
Mar 08 15:53:20 server2 pacemakerd[3035]:   notice: Caught 'Terminated' signal
Mar 08 15:53:20 server2 crmd[3107]:   notice: Caught 'Terminated' signal
Mar 08 15:53:20 server2 crmd[3107]:  warning: Input I_SHUTDOWN received in state S_TRANSITION_ENGINE from crm_shutdown
Mar 08 15:53:20 server2 corosync[2896]: Mar 08 15:53:20 info    [QB    ] withdrawing server sockets
Mar 08 15:53:20 server2 corosync[2896]:   [QB    ] withdrawing server sockets
Mar 08 15:53:20 server2 crmd[3107]:    error: Connection to the CPG API failed: Library error (2)
Mar 08 15:53:20 server2 cib[3098]:    error: Connection to the CPG API failed: Library error (2)
Mar 08 15:53:20 server2 stonith-ng[3099]:    error: Connection to cib_rw failed
Mar 08 15:53:20 server2 stonith-ng[3099]:    error: Connection to cib_rw[0x55bca9f8e870] closed (I/O condition=17)
Mar 08 15:53:20 server2 attrd[3103]:    error: Connection to cib_rw failed
Mar 08 15:53:20 server2 attrd[3103]:    error: Connection to cib_rw[0x563098faa810] closed (I/O condition=17)
Mar 08 15:53:20 server2 lrmd[3100]:    error: Connection to stonith-ng failed
Mar 08 15:53:20 server2 lrmd[3100]:    error: Connection to stonith-ng[0x55c823390ed0] closed (I/O condition=17)
Mar 08 15:53:20 server2 pengine[3104]:   notice: Caught 'Terminated' signal
Mar 08 15:53:20 server2 pacemakerd[3035]:    error: Connection to the CPG API failed: Library error (2)
Mar 08 15:53:20 server2 corosync[2896]: Mar 08 15:53:20 info    [QB    ] withdrawing server sockets
Mar 08 15:53:20 server2 corosync[2896]:   [QB    ] withdrawing server sockets
Mar 08 15:53:20 server2 systemd[1]: pacemaker.service: Main process exited, code=exited, status=107/n/a
Mar 08 15:53:20 server2 systemd[1]: pacemaker.service: Failed with result 'exit-code'.
Mar 08 15:53:20 server2 corosync[2896]: Mar 08 15:53:20 info    [QB    ] withdrawing server sockets
Mar 08 15:53:20 server2 corosync[2896]:   [QB    ] withdrawing server sockets
Mar 08 15:53:20 server2 systemd[1]: Stopped Pacemaker High Availability Cluster Manager.
```

**Comment by jnpkrn** [comment]
Hello,

On 08/03/19 16:05 +0000, Louis-Philippe F wrote:
> ```log
> Mar 08 15:53:20 server2 Filesystem(net-home-bind)[42866]: INFO: sending signal TERM to: root      3035     1  0 Mar07 ?        
> Mar 08 15:53:20 server2 pacemakerd[3035]:   notice: Caught 'Terminated' signal
> ```

I can imagine that pacemaker itself uses some files from
"net-home-bind" mount, and when this mount is to be terminated
(as a direct consequence of putting the node to standby?),
when the umount won't happen in a timely fashion, fuser or
a similar detector will discover that it may be pacemaker
that's blocking this unmounting, hence its death is in order,
and that's the end of story for this node to be a sane
cluster member.

Don't ever let pacemaker consume files from volatile filesystems
(it in addition happens to manage and hence this deadlock resolution
is a nice full circle backfiring -- am I right?).

Can you attest this scenario could be the case here?

If not, it could be some sort of bug in the resource agent.
Speaking of it, it shall perhaps realize such a deadlock on its
own and at least clarify the situation with some extra message
to the log even if the outcome will remain the same.

Regardless, this is hardly a pcs bug per se.

-- 
Jan (Poki)

**Comment by jnpkrn** [comment]
@computer045, I see you've closed the issue by the time you've received
the first response, but answering the basic question of how you got into
the guessed/estimated scenario would provide a very useful data point,
which `pacemaker`/`corosync` cluster stack could possibly benefit from in
future considerations implying a collective net gain, e.g.:

- if the scenario can be prevented on the higher-level management tool
  level (like `pcs`) directly, it might be worth it

- if the scenario can be prevented with making the resource agent
  (`ocf:heartbeat:Filesystem`) little smarter about not killing `pacemaker`
  nor any other stack-native daemon, or at least log verbosely about
  that unexpected scenario, it might be worth it as well

- possibly, it could be downright a bug in the resource agent?

Thanks for sharing these lessons learnt, we will make a good use
of them.

**Comment by computer045** [comment]
The problem was that if you don't kill the resources in the right order, pcsd crashes and takes other services with it as well.

**Comment by jnpkrn** [comment]
@computer045 sorry for sticking with your case, but it seems we indeed
have something quite interesting(ly dangerous) ahead of us thanks to
your discovery, and at the same time, I think your current interpretation
is slightly off -- `pacemakerd` that gets terminated per your log has,
in fact, little to do with `pcsd` (or `pcs` for that matter).

Will try to make it as easy as possibly if you are willing to cooperate
further (thank you in advance in that case), just a single question at
this time:

- does `Filesystem(net-home-bind)` from the log indeed match a configured
  `ocf:heartbeat:Filesystem` resource configured within the cluster?

**Comment by computer045** [comment]
I am willing to cooperate. You can reopen the issue if necessary.

To answer your question, yes it is a `ocf:heartbeat:Filesystem` resource.
To put things in context, here is the part of my cib.xml that is implicated in this error:

```xml
<clone id="home-vg-clone">
    <primitive class="ocf" id="home-vg" provider="heartbeat" type="LVM">
        <instance_attributes id="home-vg-instance_attributes">
        <nvpair id="home-vg-instance_attributes-volgrpname" name="volgrpname" value="homevg"/>
        </instance_attributes>
        <operations>
        <op id="home-vg-methods-interval-0s" interval="0s" name="methods" timeout="5"/>
        <op id="home-vg-monitor-interval-10" interval="10" name="monitor" timeout="30"/>
        <op id="home-vg-start-interval-0s" interval="0s" name="start" timeout="30"/>
        <op id="home-vg-stop-interval-0s" interval="0s" name="stop" timeout="30"/>
        </operations>
    </primitive>
    <meta_attributes id="home-vg-clone-meta_attributes"/>
</clone>
<primitive class="ocf" id="home-fs" provider="heartbeat" type="Filesystem">
        <instance_attributes id="home-fs-instance_attributes">
          <nvpair id="home-fs-instance_attributes-device" name="device" value="/dev/mapper/homevg-home"/>
          <nvpair id="home-fs-instance_attributes-directory" name="directory" value="/exports/home"/>
          <nvpair id="home-fs-instance_attributes-fstype" name="fstype" value="xfs"/>
        </instance_attributes>
        <operations>
          <op id="home-fs-monitor-interval-20" interval="20" name="monitor" timeout="40"/>
          <op id="home-fs-notify-interval-0s" interval="0s" name="notify" timeout="60"/>
          <op id="home-fs-start-interval-0s" interval="0s" name="start" timeout="60"/>
          <op id="home-fs-stop-interval-0s" interval="0s" name="stop" timeout="60"/>
        </operations>
      </primitive>
<primitive class="ocf" id="net-home-bind" provider="heartbeat" type="Filesystem">
    <instance_attributes id="net-home-bind-instance_attributes">
        <nvpair id="net-home-bind-instance_attributes-device" name="device" value="/exports/home/"/>
        <nvpair id="net-home-bind-instance_attributes-directory" name="directory" value="/net/home/"/>
        <nvpair id="net-home-bind-instance_attributes-fstype" name="fstype" value="none"/>
        <nvpair id="net-home-bind-instance_attributes-options" name="options" value="bind"/>
    </instance_attributes>
    <operations>
        <op id="net-home-bind-monitor-interval-20" interval="20" name="monitor" timeout="40"/>
        <op id="net-home-bind-notify-interval-0s" interval="0s" name="notify" timeout="60"/>
        <op id="net-home-bind-start-interval-0s" interval="0s" name="start" timeout="60"/>
        <op id="net-home-bind-stop-interval-0s" interval="0s" name="stop" timeout="60"/>
    </operations>
</primitive>
```

I have a lvm volume, a filesystem mount and a filesystem bind that are managed by pacemaker. On `pcs node standby`, if they are not shutdown in the right order, it causes the crash.

**Comment by jnpkrn** [comment]
Thanks for the response!  I don't have privileges to reopen the issue
but that's just a formality.

I'd like to ask you for two new diagnostic steps to be run just before
you trigger `pcs node standby` in your reproducer, as root:

```
lsof -w -p $(pidof pacemakerd) -a / | sort -k 9
```

and

```
grep /net/home /etc/mtab
```

Sharing the outputs of these as taken at the described moment
could possibly shed some light into your reproducer.

**Comment by computer045** [comment]
Here are the 2 outputs before doing the failover :

```sh
root@server1:~# lsof -w -p $(pidof pacemakerd) -a / | sort -k 9
pacemaker 56819 root  rtd    DIR  253,0     4096      96 /
pacemaker 56819 root  mem    REG  253,0   170960 8409329 /lib/x86_64-linux-gnu/ld-2.27.so
pacemaker 56819 root  mem    REG  253,0    66800 8409310 /lib/x86_64-linux-gnu/libbz2.so.1.0.4
pacemaker 56819 root  mem    REG  253,0  2030544 8409328 /lib/x86_64-linux-gnu/libc-2.27.so
pacemaker 56819 root  mem    REG  253,0    14560 8409314 /lib/x86_64-linux-gnu/libdl-2.27.so
pacemaker 56819 root  mem    REG  253,0    96616 8409334 /lib/x86_64-linux-gnu/libgcc_s.so.1
pacemaker 56819 root  mem    REG  253,0   153984 8409225 /lib/x86_64-linux-gnu/liblzma.so.5.2.2
pacemaker 56819 root  mem    REG  253,0  1700792 8409235 /lib/x86_64-linux-gnu/libm-2.27.so
pacemaker 56819 root  mem    REG  253,0    47568 8409201 /lib/x86_64-linux-gnu/libnss_files-2.27.so
pacemaker 56819 root  mem    REG  253,0   464824 8409237 /lib/x86_64-linux-gnu/libpcre.so.3.13.3
pacemaker 56819 root  mem    REG  253,0   144976 8409269 /lib/x86_64-linux-gnu/libpthread-2.27.so
pacemaker 56819 root  mem    REG  253,0    31680 8409228 /lib/x86_64-linux-gnu/librt-2.27.so
pacemaker 56819 root  mem    REG  253,0    27112 8410576 /lib/x86_64-linux-gnu/libuuid.so.1.3.0
pacemaker 56819 root  mem    REG  253,0   116960 8409267 /lib/x86_64-linux-gnu/libz.so.1.2.11
pacemaker 56819 root  mem    REG  253,0    34896  955507 /usr/lib/libpils.so.2.0.0
pacemaker 56819 root  mem    REG  253,0    14320  965873 /usr/lib/x86_64-linux-gnu/libcfg.so.6.0.0
pacemaker 56819 root  mem    REG  253,0    18480  965875 /usr/lib/x86_64-linux-gnu/libcmap.so.4.1.0
pacemaker 56819 root  mem    REG  253,0     5760  965865 /usr/lib/x86_64-linux-gnu/libcorosync_common.so.4.0.0
pacemaker 56819 root  mem    REG  253,0    22576  965877 /usr/lib/x86_64-linux-gnu/libcpg.so.4.1.0
pacemaker 56819 root  mem    REG  253,0    92640  970086 /usr/lib/x86_64-linux-gnu/libcrmcluster.so.4.3.1
pacemaker 56819 root  mem    REG  253,0   363736  970074 /usr/lib/x86_64-linux-gnu/libcrmcommon.so.3.8.0
pacemaker 56819 root  mem    REG  253,0    31032   36480 /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
pacemaker 56819 root  mem    REG  253,0  1133872   23666 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.3
pacemaker 56819 root  mem    REG  253,0   526688   36547 /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.2
pacemaker 56819 root  mem    REG  253,0  1457760   36531 /usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.10
pacemaker 56819 root  mem    REG  253,0   211704   36444 /usr/lib/x86_64-linux-gnu/libhogweed.so.4.4
pacemaker 56819 root  mem    REG  253,0 26904264   36548 /usr/lib/x86_64-linux-gnu/libicudata.so.60.2
pacemaker 56819 root  mem    REG  253,0  1792008   36438 /usr/lib/x86_64-linux-gnu/libicuuc.so.60.2
pacemaker 56819 root  mem    REG  253,0   116656   36537 /usr/lib/x86_64-linux-gnu/libidn2.so.0.3.3
pacemaker 56819 root  mem    REG  253,0    39272  950468 /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1
pacemaker 56819 root  mem    REG  253,0   219304   36492 /usr/lib/x86_64-linux-gnu/libnettle.so.6.4
pacemaker 56819 root  mem    REG  253,0  1237640   36428 /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.3.0
pacemaker 56819 root  mem    REG  253,0   147168  965867 /usr/lib/x86_64-linux-gnu/libqb.so.0.18.1
pacemaker 56819 root  mem    REG  253,0    10224  965879 /usr/lib/x86_64-linux-gnu/libquorum.so.5.0.0
pacemaker 56819 root  mem    REG  253,0  1594832   25654 /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25
pacemaker 56819 root  mem    REG  253,0    65280  970084 /usr/lib/x86_64-linux-gnu/libstonithd.so.2.2.4
pacemaker 56819 root  mem    REG  253,0    75776   36470 /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.5
pacemaker 56819 root  mem    REG  253,0  1562664   36550 /usr/lib/x86_64-linux-gnu/libunistring.so.2.1.0
pacemaker 56819 root  mem    REG  253,0  1834232    1377 /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.4
pacemaker 56819 root  mem    REG  253,0   247952  965901 /usr/lib/x86_64-linux-gnu/libxslt.so.1.1.29
pacemaker 56819 root  txt    REG  253,0    50496 4715131 /usr/sbin/pacemakerd
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
```

```sh
root@server1:~# grep /net/home /etc/mtab
/dev/mapper/homevg-home /net/home xfs rw,relatime,attr2,inode64,sunit=32,swidth=32768,noquota 0 0
```

**Comment by jnpkrn** [comment]
Thanks, thought it will shed some light, alas, didn't happen.

With the first output, we can see that only these directory-level
paths might be affected:

```
/
/lib/x86_64-linux-gnu/
/usr/lib/
/usr/lib/x86_64-linux-gnu
/usr/sbin
```

(vaguely, it's strange that a log file is missing in that output,
but perhaps it's because no logging to file is configured)

With the second output, we can observe that `/net/home` mount point
doesn't carry any nested mount points for other file systems.

* * *

Now, I should explain my reasoning, so we can track it down:

- if you have a look at `/usr/lib/ocf/resource.d/heartbeat/Filesystem`
  (https://github.com/ClusterLabs/resource-agents/blob/v4.2.0/heartbeat/Filesystem#L509)
  the logic there is arranged in a way that before involving `umount`,
  all detected sub-mounts are put into a to-do list together with the
  managed mount point itself at the end of list, and

- for each item on this list, `fuser` program is involved to detect
  every and each process that is currently holding a handle to some
  file/directory on that very mount point from the list, and

- each such process is signalled `SIGTERM` (`SIGKILL` in the second
  round if still around after some timeout)

* * *

What I am trying to find is a *clue* as to why `pacemaker` would ever
appear on that list of processes to be killed:

* with the checks per above, I think we proved that `pacemakerd` has
  no _direct_ involvement with whatever file on `/net/home` incl.
  it's sub-mounts

* what cannot be observed this easily though, is a hidden/indirect
  involvement, in case of:

  -  there are sym-/hard-links from any part of the above paths
     to `/net/home`

  - `/usr/lib/libpils.so.2.0.0`, library I have no experience with
    (since it is not used in Fedora/EL tradition of pacemaker builds)
    possibly has some intermittent involvement with `/net/home`
    (directly or not)

If this doesn't ring any bell, let's try an experiment:

1. get the cluster environment where you normally run `pcs node standby`
   to get the reported failure, but don't run this command

2. instead, run the following, but first read the note below:

```
pcs resouce unmanage net-home-bind
crm_resource -r net-home-bind --force-stop --verbose --verbose
```

If `pacemakerd` will get selected as a victim for described graceful
filesystem evacuation again, the log from the `crm_resource` command
shall be clear about the cause of this decision (what made `Filesystem`
resource agent act like that).

* * *

Finally, you haven't provided which constraints you have configured,
but apparently, you should consider the `ordering` constraint
between `home-vg-clone` and `home-fs`, and `group`ing `home-fs`
with `net-home-bind` (hopefully I got this right).

**Comment by jnpkrn** [comment]
Good news, @computer045, was able to track that down to bug in the
`Filesystem` resource agent, I believe, please follow there:
https://github.com/ClusterLabs/resource-agents/issues/1304

**Comment by computer045** [comment]
Thank you. I'm glad you found the bug. I'll be following that issue too.

**Comment by jnpkrn** [comment]
It more a wider systemic flaw of never considering consequences of

1. running semantically-matching instances of the agent in parallel

2. not preventing some patterns of agents' usage, or conversely,
   enforcing some constraints to be used unconditionally for
   the configuration to be allowed

To untwist it, we probably need a top-down approach, hence stating
the expectations clearly in the OCF standard, as proposed, for #1,
in that resource-agents issue and possibly discussed in relation to
https://github.com/ClusterLabs/OCF-spec/pull/21

In your very case, @computer045, it looks like proper ordering
suggested at the end of the longish comment above will effectively
help.

This very issue can then be closed again when you confirm
the suggestion works, othewise we can assist you further.

**Comment by tomjelinek** [comment]
There is nothing to be done in pcs right now. The discussion has moved to resource agents.
