### ISSUE TITLE
CRM_alert_task and other entries are NULL for "node" pcs alert when other node joins the cluster.

### ISSUE THREAD

**Issue by rohsaini** [ClusterLabs/pcs#199]
**PCS Version:**
[root@rohit-hng1 UD-36554]# rpm -qa|grep pcs
pcs-0.9.158-6.el7.centos.x86_64
[root@rohit-hng1 UD-36554]# rpm -qa|grep pacemaker
pacemaker-libs-1.1.16-12.el7.x86_64
pacemaker-cli-1.1.16-12.el7.x86_64
pacemaker-1.1.16-12.el7.x86_64
pacemaker-cluster-libs-1.1.16-12.el7.x86_64

**Issue:**
CRM_alert_task and other entries are NULL for "node" pcs alert when other node joins the cluster.

2019-03-08T16:23:41.191806+05:30 tigana PcsAlert: kind [node], task [NULL], rsc_name [NULL], desc [member], status [1]  <<<<<<<<<<<<<
2019-03-08T16:58:50.934503+05:30 tigana PcsAlert: kind [node], task [NULL], rsc_name [NULL], desc [member], status [1]  <<<<<<<<<<<<<
2019-03-08T16:15:50.570641+05:30 tigana PcsAlert: kind [resource], task [monitor], rsc_name [fence-uc-orana], desc [ok], status [0]

**Comment by tomjelinek** [comment]
I would guess that is perfectly OK. Node joining a cluster has nothing to do with any resources directly, therefore no resource is mentioned in the alert. Also, task seems to be related to a resource (monitor is definitely a resource action) and when there is no resource, the task being NULL seems fine.
[Pacemaker documentation](http://clusterlabs.org/pacemaker/doc/en-US/Pacemaker/2.0/html-single/Pacemaker_Explained/index.html#_writing_an_alert_agent) confirms I am right, resource name and task are set only for resource related alerts.

Anyway, this is a pacemaker thing so I recommend you to contact pacemaker developers either at [ClusterLabs users mailinglist](https://oss.clusterlabs.org/mailman/listinfo/users) or [pacemaker bugzilla](https://bugs.clusterlabs.org/).

**Comment by rohsaini** [comment]
Thanks Tomas.
