### ISSUE TITLE
Key Exchange Algorithm cannot be configured

### ISSUE THREAD

**Issue by tlx1** [ClusterLabs/pcs#200]
Hi all,

during our routine netscan, it was discovered that pcsd uses DH with insufficient strength for key exchange:

> nmap  -p 2224 -Pn localhost --script +ssl-enum-ciphers |& sed -n '/PORT/,/MAC/p'
> PORT     STATE SERVICE
> 2224/tcp open  efi-mg
> | ssl-enum-ciphers: 
> |   TLSv1.2: 
> |     ciphers: 
> |       TLS_DHE_RSA_WITH_AES_128_CBC_SHA (dh 1024) - A
> |       TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (dh 1024) - A
> |       TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 1024) - A
> |       TLS_DHE_RSA_WITH_AES_256_CBC_SHA (dh 1024) - A
> |       TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (dh 1024) - A
> |       TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 1024) - A
> |       TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA (dh 1024) - A
> |       TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA (dh 1024) - A
> |     compressors: 
> |       NULL
> |     cipher preference: client
> |     warnings: 
> |       Key exchange (dh 1024) of lower strength than certificate key
> |_  least strength: A
> 
> Nmap done: 1 IP address (1 host up) scanned in 0.39 seconds

Sadly, we did not find any sort of config param to change that. Only the cipher list ist configureable.

Would it be possible to add that option, or if it already exists, to point us in the right direction to modify it?

Thanks!

**Comment by tomjelinek** [comment]
Hi tlx1,

I added new option to pcsd config file for configuring DH key length in https://github.com/ClusterLabs/pcs/commit/a44b400b34312ea36b2bcf50bd443b9e1fbd1b58 . There was no way for setting DH key length before.
