### ISSUE TITLE
IPv6 notation for ocf:heartbeat:IPaddr2

### ISSUE THREAD

**Issue by rajubi1981** [ClusterLabs/pcs#205]
Hi,

We are trying to add a resource to a group. For us only the short IPv6 notation works.

fd5d:d50a:8c17:2040::251

`pcs resource create MNGT_VIP ocf:heartbeat:IPaddr2 ip=fd5d:d50a:8c17:2040::251 op monitor interval=10s --group MNGT`

But if we try the below IPv6 notation 

fd5d:d50a:8c17:2040:0000:0000:0000:0251
fd5d:d50a:8c17:2040:0:0:0:0251

And same with Upper Case notation. 

We wanted to know is there any restriction from pcs package for specific IPv6 notation.

Can you please help.

**Comment by tomjelinek** [comment]
There is no restriction in pcs regarding IPv6 format for IPaddr2 (or any other) resource. All your formats work for me (pcs-0.9.167, pcs-0.10.1), the VIP resource is successfully created. Did you get any error messages? What is not working for you?
