### ISSUE TITLE
[Question] About the description of rule setting.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/pcs#207]
Hi All,

In Pacemaker cib.xml, it is possible to set the following rules for resources.

```
<primitive id="mySpecialRsc" class="ocf" type="Special" provider="me">
   <instance_attributes id="special-node1" score="3">
    <rule id="node1-special-case" score="INFINITY" >
     <expression id="node1-special-case-expr" attribute="#uname"
       operation="eq" value="node1"/>
    </rule>
    <nvpair id="node1-interface" name="interface" value="eth1"/>
   </instance_attributes>
   <instance_attributes id="special-node2" score="2" >
    <rule id="node2-special-case" score="INFINITY">
     <expression id="node2-special-case-expr" attribute="#uname"
       operation="eq" value="node2"/>
    </rule>
    <nvpair id="node2-interface" name="interface" value="eth2"/>
    <nvpair id="node2-port" name="port" value="8888"/>
   </instance_attributes>
   <instance_attributes id="defaults" score="1" >
    <nvpair id="default-interface" name="interface" value="eth0"/>
    <nvpair id="default-port" name="port" value="9999"/>
   </instance_attributes>
</primitive>
```
 - https://clusterlabs.org/pacemaker/doc/en-US/Pacemaker/2.0/html/Pacemaker_Explained/_using_rules_to_control_resource_options.html#idm140043945506624

I looked at the help etc, but could not find the way of this description.

Can I set this rule in pcs?
If so, what kind of syntax is it?

Best Regards,
Hideo Yamauchi.

**Comment by tomjelinek** [comment]
Hi Hideo,

Multiple `instance_attributes` and `meta_attributes` elements with rules are not supported by pcs. We track a request for the feature in [bz1250744](https://bugzilla.redhat.com/show_bug.cgi?id=1250744). It has always been a low priority feature, though. On top of that it requires a lot of changes to be done in pcs. So I don't see it coming to pcs anytime soon.

You are of course free to set these rules in cib.xml manually. If you do, do not try changing them by pcs, it would mess the attributes up.

**Comment by HideoYamauchi** [comment]
Hi Tomas,

All right!
Thanks!

Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Tomas,

I am closing this issue because I am tracking it with bz1250744.

Many thanks,
Hideo Yamauchi.
