### ISSUE TITLE
python testsuite errors in set_sync_options

### ISSUE THREAD

**Issue by vvidic** [ClusterLabs/pcs#210]
Hello,

Running python testsuite in pcs 0.10.3 produces these two errors:

```
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f5695c893b0>, HTTPResponse(_body=None,_error_is_response_code=False,buffer=None,code=599,effective_url='http://127.0.0.1:41859/remote/set_sync_options',error=HTTP 599: Stream closed,headers=<tornado.httputil.HTTPHeaders object at 0x7f5694985350>,reason='Unknown',request=<tornado.httpclient.HTTPRequest object at 0x7f56948beb10>,request_time=0.05209493637084961,start_time=1567190858.045878,time_info={}))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/usr/lib/python3/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/tornado/httpclient.py", line 290, in handle_response
    future.set_exception(response.error)
asyncio.base_futures.InvalidStateError: invalid state

ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f5695c89b90>, HTTPResponse(_body=None,_error_is_response_code=False,buffer=None,code=599,effective_url='http://127.0.0.1:42553/remote/set_sync_options',error=HTTP 599: Stream closed,headers=<tornado.httputil.HTTPHeaders object at 0x7f56948abf50>,reason='Unknown',request=<tornado.httpclient.HTTPRequest object at 0x7f5694a163d0>,request_time=0.051965951919555664,start_time=1567190858.104884,time_info={}))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/usr/lib/python3/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/tornado/httpclient.py", line 290, in handle_response
    future.set_exception(response.error)
asyncio.base_futures.InvalidStateError: invalid state
```
but the tests don't fail. Not sure what to make of it, any ideas?

**Comment by idevat** [comment]
Hi,

it looks like you are using an old version of tornado. We have switched to `tornado 6.x` (`6.0.3`) to support `python 3.8`. We forgot to mention it in the changelog, sorry for that.

**Comment by vvidic** [comment]
On Mon, Sep 02, 2019 at 12:02:56AM -0700, Ivan Devát wrote:
> it looks like you are using an old version of tornado. We have switched to
> `tornado 6.x` (`6.0.3`) to support `python 3.8`. We forgot to mention it in
> the changelog, sorry for that.

Thanks for the info, I need to wait for tornado 6 to be included in Debian than.

-- 
Valentin

**Comment by vvidic** [comment]
Would it be possible to make it work with tornado 5 too? It seems tornado 6 only supports python 3 so it will take some time until it replaces tornado 5 (python 2 compatibility is still required for other Debian packages).

**Comment by idevat** [comment]
Hi,
there were some issues during `python 3.8` support works, which are not solved in `tornado 5`. However, the changes in `pcs` code base are not too extensive. They can be found in the following commits:
* 054018d0 - `tornado.gen.Task` removal
* 3f7242df, ddede7d8 - test fix
* 65c52cd1 - just README.md

Maybe you can do a downstream patch. Or a package `python3-tornado` similarly to e.g. `python3-pip`?

**Comment by vvidic** [comment]
On Wed, Oct 02, 2019 at 05:54:01AM -0700, Ivan Devát wrote:
> there were some issues during `python 3.8` support works, which are not solved in `tornado 5`. However, the changes in `pcs` code base are not too extensive. They can be found in the following commits:
> * 054018d0 - `tornado.gen.Task` removal
> * 3f7242df, ddede7d8 - test fix
> * 65c52cd1 - just README.md
> 
> Maybe you can do a downstream patch. Or a package `python3-tornado` similarly to e.g. `python3-pip`?

Thanks, I've reverted the test that was causing problems. Hope it works
like that until python 2 is removed and tornado 6 gets included in Debian :)

-- 
Valentin
