### ISSUE TITLE
Using pcs with Ansible

### ISSUE THREAD

**Issue by floackermann** [ClusterLabs/pcs#211]
Hi All,

i am trying to use pcs with Ansible.
In my playbook i'm trying to use the command:

`pcs cluster auth server1 server -u hacluster -p ****** `.

The playbook gets stuck there because it waits for input:

`Please authenticate yourself to the local pcsd`.

I tried runnig it as the hacluster user, with the same result.
Is there a way to put the authentication into the command, so that it doesnt wait for the input?

Thanks for your help,

Flo

**Comment by tomjelinek** [comment]
Hi,

The preferred solution is to use the `pcs client local-auth` command added in pcs 0.9.167. If you cannot upgrade pcs for whatever reason, you can either run pcs as the root user or redirect standard input like this: `printf "hacluster\n*****\n" | pcs cluster auth node1 node2 -u hacluster -p *****`
