### ISSUE TITLE
ocf:heartbeat:redis master/slave setup fails (on PCS 0.10?)

### ISSUE THREAD

**Issue by AquaL1te** [ClusterLabs/pcs#214]
# Summary
I ran into an issue with Redis in combination with PCS. I want to manage a Redis master/slave setup with PCS. On CentOS 7 it works fine, but on Debian 10 and Fedora 30 it doesn't work. In the bottom of this issue there is an overview of running software versions.

# Troubleshooting
On all systems, the following example is included in the man page:
```
EXAMPLE PCS
       The following is an example configuration for a redis resource using pcs(8)

           pcs resource create p_redis ocf:heartbeat:redis \
             op monitor depth="0" timeout="60s" interval="45s" \
             op monitor role="Master" depth="0" timeout="60s" interval="20s" \
             op monitor role="Slave" depth="0" timeout="60s" interval="60s" --master
```

The example above doesn't work on any of the distributions. The `depth` value and `--master` options are not supported.

For CentOS 7 I had to use the following command: `pcs resource create redis ocf:heartbeat:redis op start timeout=300s op monitor interval=5s op monitor interval=3s role=Master master` To create a master/slave setup.

However, this can't be replicated for other distributions. For example on Debian 10:
```
pcs resource create redis ocf:heartbeat:redis op start timeout=300s op monitor interval=5s op monitor interval=3s role=Master master
Error: When using 'op' you must specify an operation name and at least one option
```

I then have to change the command to: `pcs resource create redis ocf:heartbeat:redis op monitor interval=10s role=Master op monitor role=Slave` for the command to run without errors. However, I don't see a master/slave setup with `pcs status`. It's a single instance:

```
# pcs status
Cluster name: neobits
Stack: corosync
Current DC: rp1 (version 2.0.1-9e909a5bdd) - partition with quorum
Last updated: Fri Oct 18 11:07:24 2019
Last change: Fri Oct 18 11:05:24 2019 by root via cibadmin on rp1

2 nodes configured
2 resources configured

Online: [ rp1 rp2 ]

Full list of resources:

 Resource Group: grp-www
     ip-www     (ocf::heartbeat:IPaddr2):       Started rp1
 redis  (ocf::heartbeat:redis): Started rp2

Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled
```

When compared to the CentOS 7 output, where a master/slave is configured:
```
# pcs status
Cluster name: cluster1
Stack: corosync
Current DC: rp1 (version 1.1.20-5.el7_7.1-3c4c782f70) - partition with quorum
Last updated: Fri Oct 18 05:10:45 2019
Last change: Fri Oct 18 05:10:37 2019 by root via crm_resource on rp1

2 nodes configured
3 resources configured

Online: [ rp1 rp2 ]

Full list of resources:

 VIP    (ocf::heartbeat:IPaddr2):       Started rp1
 Master/Slave Set: redis-master [redis]
     Masters: [ rp1 ]
     Slaves: [ rp2 ]

Daemon Status:
  corosync: active/disabled
  pacemaker: active/disabled
  pcsd: active/enabled
```

# Conclusion
For sure the commands have changed and the man pages are out of date. Furthermore, it seems to work fine on CentOS 7, but on newer software (on Debian 10 and Fedora 30) the same master/slave setup can't be established. My question therefore is; am I doing something wrong in the commands? Or is there a bug in play?

# Software versions
## CentOS 7
```
# rpm -qa pcs resource-agents redis
pcs-0.9.167-3.el7.centos.1.x86_64
redis-3.2.12-2.el7.x86_64
resource-agents-4.1.1-30.el7_7.2.x86_64
```

## Fedora 30
```
# rpm -qa pcs resource-agents redis
redis-5.0.6-1.fc30.x86_64
resource-agents-4.3.0-1.fc30.x86_64
pcs-0.10.3-1.fc30.x86_64
```

## Debian 10
```
# dpkg -l pcs resource-agents redis-server
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name            Version           Architecture Description
+++-===============-=================-============-====================================================
ii  pcs             0.10.1-2          all          Pacemaker Configuration System
ii  redis-server    5:5.0.3-4+deb10u1 amd64        Persistent key-value database with network interface
ii  resource-agents 1:4.2.0-2         amd64        Cluster Resource Agents
```

**Comment by tomjelinek** [comment]
Thank you for complete and detailed description of your issue.

Pacemaker 2.0.0 renamed master/slave resources to promotable clones. Pcs 0.10 followed with the same change. The roles, however, have not been renamed yet.

The depth option never worked correctly, I think. Use OCF_CHECK_LEVEL instead which is the right way of doing the same thing.

So the example command should look like this:
```
pcs resource create p_redis ocf:heartbeat:redis \
op monitor OCF_CHECK_LEVEL=0 timeout=60s interval=45s \
op monitor role=Master OCF_CHECK_LEVEL=0 timeout=60s interval=20s \
op monitor role=Slave OCF_CHECK_LEVEL=0 timeout=60 interval=60 \
promotable
```
I'm not sure why they set OCF_CHECK_LEVEL to 0 which is the default, but that's not a big deal.

And your command should be:
```
pcs resource create redis ocf:heartbeat:redis \
op start timeout=300s op monitor interval=5s op monitor interval=3s role=Master \
promotable
```

Which manpage is the example from?

**Comment by AquaL1te** [comment]
That command indeed does the trick, thanks! The example was included in [man ocf_heartbeat_redis](https://manpages.debian.org/testing/resource-agents/ocf_heartbeat_redis.7.en.html). Which is included on Debian 10 and Fedora 30 (probably more distributions are out of sync with the documentation).

Also with `pcs resource describe ocf:heartbeat:redis` there is no specific mention of the `promotable` switch.

**Comment by tomjelinek** [comment]
There is no reason for the `promotable` keyword to be included in `pcs resource describe ocf:heartbeat:redis`. It is a generic keyword / functionality which can be used with many other resources. The keyword is described in pcs man page and the functionality in Pacemaker documentation.

I filed a bug against resource-agents to fix their man page, you can track it at https://bugzilla.redhat.com/show_bug.cgi?id=1763249
