### ISSUE TITLE
pcs result isn't correct

### ISSUE THREAD

**Issue by jiang4357291** [ClusterLabs/pcs#215]
![image](https://user-images.githubusercontent.com/38097280/67458355-99455400-f668-11e9-8364-e3cd25d542c6.png)

I use pacemaker created a systemd:nfs-ganesha resource.But sometimes i found that the ganesha process has already failed and exited,but pcs shows that it's statred,and pacemaker didn't try to pull the failed nfs-ganesha process.

**Comment by tomjelinek** [comment]
It is actually pacemaker who shows that it's started. Pcs just prints output from pacemaker in this case.

This is either pacemaker and / or resource agent issue. I suggest you to send this question together with your cluster status, configuration and logs to users@clusterlabs.org mailinglist as pacemaker / resource agents / ganesha experts do not read and respond to pcs issues on github.

**Comment by jiang4357291** [comment]
> It is actually pacemaker who shows that it's started. Pcs just prints output from pacemaker in this case.
> 
> This is either pacemaker and / or resource agent issue. I suggest you to send this question together with your cluster status, configuration and logs to [users@clusterlabs.org](mailto:users@clusterlabs.org) mailinglist as pacemaker / resource agents / ganesha experts do not read and respond to pcs issues on github.

Thanks for that,i'll try to send email to the mailinglist.
