### ISSUE TITLE
pcs install problem

### ISSUE THREAD

**Issue by alias154** [ClusterLabs/pcs#218]
Hello,

I can try install on pcs froum source. Install all requirements
but have this problem:

>   make install
....
Installing json 2.1.0 with native extensions
Installing mustermann 1.0.3
Installing open4 1.3.4
Installing rack 2.0.6
Installing rack-protection 2.0.4
Installing rack-test 1.1.0
Installing tilt 2.0.9
Installing sinatra 2.0.4
Bundle complete! 10 Gemfile dependencies, 12 gems now installed.
Bundled gems are installed into `./vendor/bundle`
#ffi makes symlink with absolute path. Let's change it to relative path.
for fname in `ls vendor/bundle/ruby/gems/ffi-"1.9.25"/ext/ffi_c/libffi-*/include/ffitarget.h`; do \
        if [[ -L "$fname" ]]; then \
                target=$(readlink $fname | sed "s~.*/vendor/bundle/ruby/gems/ffi-"1.9.25"/ext/ffi_c\(/libffi/src/[^/]\+/ffitarget.h\)~../..\1~"); \
                rm $fname; \
                ln -s $target $fname; \
        fi; \
done;
ls: cannot access vendor/bundle/ruby/gems/ffi-1.9.25/ext/ffi_c/libffi-*/include/ffitarget.h: No such file or directory
make[1]: Leaving directory `/root/tmp/pcs-0.10.4/pcsd'
install -d -m 700 /var/log/pcsd
mkdir -p /usr/lib/pcsd/
cp -r pcsd /usr/lib
install -m 644 -D pcsd/pcsd.conf /etc/sysconfig/pcsd
install -d /etc/pam.d
install -m 644 pcsd/pcsd.pam /etc/pam.d/pcsd
install -d /usr/lib/systemd/system
install -m 644 pcsd/pcsd.service /usr/lib/systemd/system/pcsd.service
install -m 700 -d /var/lib/pcsd
install -m 644 -D pcsd/pcsd.logrotate /etc/logrotate.d/pcsd
install -m644 -D pcsd/pcsd.8 /usr/share/man/man8/pcsd.8
ln -s -f /usr/share/fonts/liberation/LiberationSans-Regular.ttf /usr/lib/pcsd/public/css/LiberationSans-Regular.ttf;      ln -s -f /usr/share/fonts/liberation/LiberationSans-Bold.ttf /usr/lib/pcsd/public/css/LiberationSans-Bold.ttf;      ln -s -f /usr/share/fonts/liberation/LiberationSans-Regular.ttf /usr/lib/pcsd/public/css/LiberationSans-BoldItalic.ttf;      ln -s -f /usr/share/fonts/liberation/LiberationSans-Italic.ttf /usr/lib/pcsd/public/css/LiberationSans-Italic.ttf;      ln -s -f /usr/share/fonts/overpass/Overpass-Regular.ttf /usr/lib/pcsd/public/css/Overpass-Regular.ttf;      ln -s -f /usr/share/fonts/overpass/Overpass-Bold.ttf /usr/lib/pcsd/public/css/Overpass-Bold.ttf;

> 

But i have problem

>  ~/tmp/pcs-0.10.4#  pcs
Traceback (most recent call last):
  File "/usr/sbin/pcs", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pcs==0.10.4' distribution was not found and is required by the application
>

What are the my problems? Thanks!

**Comment by alias154** [comment]
In sys.path have right path


root@test ~/tmp/pcs-0.10.4# python3
Python 3.6.8 (default, Aug  7 2019, 17:28:10)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.path)
['', '/usr/lib64/python36.zip', '/usr/lib64/python3.6', '/usr/lib64/python3.6/lib-dynload', '/usr/local/lib64/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages', '/usr/lib64/python3.6/site-packages', '/usr/lib/python3.6/site-packages']
>>>
root@test  ~/tmp/pcs-0.10.4# ls -l /usr/local/lib/python3.6/site-packages
total 80
drwxrwxr-x 3 root root  4096 Nov 27 16:02 OpenSSL
drwxrwxr-x 8 root root  4096 Dec  2 12:23 pcs
drwxrwxr-x 2 root root  4096 Nov 28 11:52 pcs-0.10.3-py3.6.egg-info
drwxrwxr-x 2 root root  4096 Dec  2 12:23 pcs-0.10.4-py3.6.egg-info
drwxrwxr-x 5 root root  4096 Nov 28 10:38 pip
drwxrwxr-x 2 root root  4096 Nov 28 10:38 pip-19.3.1.dist-info
drwxrwxr-x 2 root root  4096 Nov 27 16:02 __pycache__
drwxrwxr-x 4 root root  4096 Nov 27 16:02 pycparser
drwxrwxr-x 2 root root  4096 Nov 27 16:02 pycparser-2.19-py3.6.egg-info
drwxrwxr-x 2 root root  4096 Nov 27 16:02 pyOpenSSL-19.1.0.dist-info
drwxrwxr-x 2 root root  4096 Nov 27 16:02 six-1.13.0.dist-info
-rw-rw-r-- 1 root root 33045 Nov 27 16:02 six.py
root@test  ~/tmp/pcs-0.10.4#

>

**Comment by tomjelinek** [comment]
I believe the issue has been resolved as described in the previous comment. If you think otherwise, feel free to reopen the issue or create a new one.
