### ISSUE TITLE
Reload resource configuration

### ISSUE THREAD

**Issue by antonionappi88** [ClusterLabs/pcs#219]
Hello,
I'm running haproxy ocf agent with pacemaker and corosync. 
So far if we changed anything in the haproxy configuration we had to restart it.

I know that I could add the reload operation to the ocf agent file but I don't see any reload option in the pcs command line that would trigger it.

Do you know how I can achieve the reload of the configuration?

Thank you in advance.
Antonio

**Comment by tomjelinek** [comment]
Hello,
There is no pcs command for reloading a resource configuration. As far as I know, it is not supported by pacemaker. For more info, see https://lists.clusterlabs.org/pipermail/users/2017-August/022594.html and https://bugzilla.redhat.com/show_bug.cgi?id=1217099

**Comment by antonionappi88** [comment]
Hello @tomjelinek,
thank you for the reply. It seems a bit stuck the situation. I'll go for a manual reload of haproxy configuration.
