### ISSUE TITLE
[booth] cannot create new booth IP when (changed mind and) removed the original booth IP resource

### ISSUE THREAD

**Issue by jnpkrn** [ClusterLabs/pcs#221]
Related to #220, when I wanted to go a single step back, remove the
original, malfunctioning `booth-booth-ip` resource, I was unable to create
a new `booth IP`, this time without mask specification.

This means pcs is not robust enough to deal with single step transitional
progress towards the requested goals, something you can imagine when
familiar with how `make` utility works: gradual backtrack down to where
the assumptions (that sources/intermediaries exist, usually) break,
and working up from there.

Such a mechanism is vital for pcs to be production ready robust
(in a nutshell: nobody can find themselves in a situation they got into
with plain pcs commands while, at the same time, not recoverable
again with just plain pcs commands, free of dismantling whole cluster),
but it seems nowhere near based on this experience.

In this very case, it cannot even be overridden with old good `--force`.

**Comment by jnpkrn** [comment]
Sorry, so `pcs booth remove` fulfills the recoverability with plain pcs
commands.  It would then be natural to offer that command or even to
trigger it on behalf of and as part of `pcs booth create ip IP` command
when the state evaluated as safe enough (e.g. resources not running).

**Comment by tomjelinek** [comment]
I don't see any issue here. As you confirmed yourself, `pcs booth remove` works just fine.

**Comment by jnpkrn** [comment]
However, that solution is not that straightforward, leaving some portion
of userbase effectively in deadlock. Solution would be to at least suggest
that, or even better, to automate it independently when safe to do so
as mentioned -- that would be the value added of _high_ level management
tool.

**Comment by jnpkrn** [comment]
That being said, I'd be in favour of reopening this issue.

It could be reworded towards more abstraction:
make pcs wise enough to recover from intersteps by redoing the
missing transitions towards the goals when safe to do so (akin to `make`),
so as to avoid operational deadlocks

**Comment by jnpkrn** [comment]
Ping?
