### ISSUE TITLE
[convenience] `pcs cluster auth` shall gain a "proxy" simplification for many-to-many one-way authentication (e.g. multisite, disaster recovery like use cases)

### ISSUE THREAD

**Issue by jnpkrn** [ClusterLabs/pcs#224]
I may be mistaken and such a feature is already in there, however in seems
a _heavy_ overkill to be forced for a simple, say, multi-site use case, to run
a particular `pcs cluster auth` command from `(|N_1| + ... + |N_x|)`
nodes for `X` clusters, where `|N_y|` denotes number of nodes in given cluster.
Certainly, it's completely unscalable to this by hand.

Therefore, this exchange from cluster A towards a cluster B
(in this particular case, the "booth IP" that is configured with
`pcs booth create ip IP` on one of the cluster B nodes):

```
# pcs cluster auth 10.37.164.52
> Username: hacluster
> Password: <entered password>
> 10.37.164.52: Authorized
```

i.e., one-off, but per this request would ideally look more like this:

```
> Username: hacluster
> Password: <entered password>
> 10.37.164.52: Authorized
> Address 10.37.164.52 stands for a node member of a cluster
> ("B"), which is a different from the one local node is member
> of ("A").
>
> Nodes of local cluster "A": <list>
> Nodes of remote cluster "B": <list>
> 
> (In particular, 10.37.164.52 stands for a virtual IP in cluster "B").
> 
> We are going to authenticate each of local cluster nodes against
> each of canonically addressed nodes within this discovered
> remote cluster.
> 
> You can terminate at any point incl. now, existing authentications
> will remain valid, and you can finalize the operation by rerunning
> it later.
> 
> Authenticating against "virt-181" node:
> Username: hacluster
> Password: <entered password>
> virt-181: Authorized for nodes of local cluster A
>     virt-158
>     virt-159
> 
> Authenticating against "virt-182" node:
> Username: hacluster
> Password: <entered password>
> virt-182: Authorized for nodes of node cluster A
>     virt-158
>     virt-159
```

Combinatorially, with 3 clusters, 2 nodes each, it would only require
`C * (C - 1)` executions, where `C` is a number of clusters to be
cross-authenticated, i.e., `3 * (3-1) = 6`.  OTOH, the old way, it would
go bonkers (sorry, markdown is not LaTeX):

```
sum
  for N_i with i going from 1 to x
  for N_j with j going from 1 to x except for i
    |N_i| * |N_j|
```

(where `|N_a|` symbol carries the already given semantics)

i.e., `((2 * 2) + (2 * 2)) + ((2 * 2) + (2 * 2)) + ((2 * 2) + (2 * 2))`,
that is `3 * (2 * (2 * 2)) = 24`, that is *4 times more work than
when the sketched request is implemented*.

Cast some math here on your own, the advantage will become
even more blatant if you increase number of clusters and/or
their particular sizes.

Original idea is that authentication would remain one-way only
(for various simplicity and trust-related reasons), but further
optimization of making it full duplex would moreover cut the
already optimized number of invocations by half, apparently.

**Comment by tomjelinek** [comment]
There is no need to authenticate all nodes against all nodes multiple times as the authentication is synced across nodes in a cluster. Just run `pcs cluster auth` once in each cluster / booth arbitrator / qdevice host and specify all nodes you want it to be authenticated against. You run the auth command as many times as many sites you have.

If you have 3 clusters (number of nodes in the clusters does not matter) and want to have all nodes from all the cluster authenticated to each other, you need to run the auth command 3 times, once for each cluster.

**Comment by jnpkrn** [comment]
> There is no need to authenticate all nodes against all nodes
> multiple times

Will gladly stand corrected, however this doesn't seem to be
a takeaway from neither pcs 0.9 nor 0.10 man page.

Perhaps this imprecise wording is at fault?

> By default all nodes are also authenticated to each other

One might expect that only the hosts particular `auth` command
deals with at the moment will be subject to this mutuality, not\
that already authenticated nodes will be involved as well in
this, or will they?

> as the authentication is synced across nodes in a cluster

This seems to answer that question (but still only the
in-cluster subset of the hosts), correct?


Or perhaps you meant that from a single node, one would trigger
the `cluster auth`/`host auth` command to each host (cluster-local
and of remote cluster) initially?  I'd suppose that default state
is usually in-cluster-auth-already-performed, so you'd want
to authenticate just against nodes of remote clusters/sites.


And there's this another dimension of the problem (if my previous
concerns can be reduced to this very one despite the mentioned
underdocumentation):

- consider you have 3 sites, 16 nodes each

- do you really consider it a viable approach to specify
  `pcs cluster auth <32 nodes>`?

IOW, where's some cluster discoverability?  Usually in this
type of tasks, it is sufficient to specify a single address
the node of particular cluster is expected to listen, and
once the requesting host is authenticated, it shall be provided
with "the discovery" of other nodes in that cluster, or the
asked node can act as a proxy.

In that case, `pcs cluster auth <2 nodes, 1 per other cluster/site each>`
would be sufficient, and you can derive, substantially more
convenient.

Can this issue be reopened with this new direction, please?
