### ISSUE TITLE
Postgresql cluster built by pcs, failure after modifying configuration

### ISSUE THREAD

**Issue by wybaron** [ClusterLabs/pcs#245]
I ran into a problem and looked forward to your help. The process of generating this problem is as follows:
In the case of non-stop service, modify the parameters **log_destination, log_min_messages , log_connections,log_disconnections,   log_hostname, log_rotation_size, log_error_verbosity,ssl**  in the postgresql.conf file.
View parameter enumeration：
```
postgres=#  select name, context from pg_settings;
                  name                  |      context      
----------------------------------------+-------------------
 ...
 log_destination                        | sighup
 log_min_messages                       | superuser
 log_connections                        | superuser-backend
 log_disconnections                     | superuser-backend
 log_hostname                           | sighup
 log_rotation_size                      | sighup
 log_error_verbosity                    | superuser
```
 ...

 **I changed ssl from off to on .**

After the modification was completed, I configured reload through the super user, and then the following situation occurred:

```
$ sudo pce status 

Full list of resources:

 PostgresVIP	(ocf::heartbeat:IPaddr2):	Stopped
 Master/Slave Set: PostgreSQLHA [PostgreSQLService]
     PostgreSQLService	(ocf::heartbeat:pgsqlms):	FAILED node1 (blocked)
     PostgreSQLService	(ocf::heartbeat:pgsqlms):	FAILED Master node3 (blocked)
     PostgreSQLService	(ocf::heartbeat:pgsqlms):	FAILED node2 (blocked)
```

**Comment by wybaron** [comment]
Because I made a backup of the configuration file, I tried to restore the backup configuration file (the backup file is the configuration file that has not been modified), but after restoring the backup configuration file, I still get this error, but when I check the cluster node, it is online In the status, I suspect that the ssl value was modified to cause the communication in the cluster to fail, which caused this problem.
```
$ sudo pcs cluster status
PCSD Status:
  node3: Online
  node1: Online
  node2: Online
```

Because I do n’t know much about the postgresql database, I would like to ask a professional. Thank you very much for helping me.

**Comment by tomjelinek** [comment]
You may have misconfigured your pgsql. That is not a pcs issue. I'm sorry we don't have much expertise with pgsql and we cannot provide further assistance. Please, post your question to users@clusterlabs.org mailing list. The list is being read by a much broader audience including people who run pgsql in their clusters and are able to help you. Be sure to post the whole cluster  configuration `'pcs config'` (or at least `'pcs resource config PostgreSQLHA'`) and status `'pcs status'`, it will make it easier to find out what's wrong.

Generally speaking, you should not start / stop / restart... resources managed by the cluster manually.

The 'PCSD Status' section only shows that pcs (cluster management tool) can connect to cluster nodes. It doesn't say anything about the actual cluster or cluster resources.
