### ISSUE TITLE
Parameter "recovery_target_timeline" MUST be set to 'latest'

### ISSUE THREAD

**Issue by wybaron** [ClusterLabs/pcs#246]
Check the status of the PCS cluster and report an error.
```
$ sudo pcs status
Failed Resource Actions:
* NginxService_monitor_60000 on node1.radar.ecological.frontier.unionbigdata.com 'OCF_PENDING' (196): call=36, status=complete, exitreason='',
    last-rc-change='Thu Apr  2 15:35:52 2020', queued=0ms, exec=0ms
* PostgreSQLService_stop_0 on node1 'invalid parameter' (2): call=83, status=complete, exitreason='Parameter "recovery_target_timeline" MUST be set to 'latest'. It is currently set to ''',
    last-rc-change='Thu May  7 11:38:03 2020', queued=0ms, exec=109ms
* PostgreSQLService_stop_0 on node3 'invalid parameter' (2): call=73, status=complete, exitreason='Parameter "recovery_target_timeline" MUST be set to 'latest'. It is currently set to ''',
    last-rc-change='Thu May  7 11:37:58 2020', queued=0ms, exec=130ms
* PostgreSQLService_stop_0 on node2 'invalid parameter' (2): call=65, status=complete, exitreason='Parameter "recovery_target_timeline" MUST be set to 'latest'. It is currently set to ''',
    last-rc-change='Thu May  7 11:37:50 2020', queued=0ms, exec=127ms

```
View the value of the parameter.
```
postgres=# show recovery_target_timeline;
 recovery_target_timeline 
--------------------------
 latest
(1 row)

```
Thank you for your help！

**Comment by tomjelinek** [comment]
You may have misconfigured your pgsql. That is not a pcs issue. I'm sorry we don't have much expertise with pgsql and we cannot provide further assistance. Please, post your question to users@clusterlabs.org mailing list. The list is being read by a much broader audience including people who run pgsql in their clusters and are able to help you. Be sure to post the whole cluster  configuration `'pcs config'` (or at least `'pcs resource config PostgreSQLHA'`) and status `'pcs status'`, it will make it easier to find out what's wrong.

**Comment by kyourselfer** [comment]
> Check the status of the PCS cluster and report an error.
> 
> ```
> $ sudo pcs status
> Failed Resource Actions:
> * NginxService_monitor_60000 on node1.radar.ecological.frontier.unionbigdata.com 'OCF_PENDING' (196): call=36, status=complete, exitreason='',
>     last-rc-change='Thu Apr  2 15:35:52 2020', queued=0ms, exec=0ms
> * PostgreSQLService_stop_0 on node1 'invalid parameter' (2): call=83, status=complete, exitreason='Parameter "recovery_target_timeline" MUST be set to 'latest'. It is currently set to ''',
>     last-rc-change='Thu May  7 11:38:03 2020', queued=0ms, exec=109ms
> * PostgreSQLService_stop_0 on node3 'invalid parameter' (2): call=73, status=complete, exitreason='Parameter "recovery_target_timeline" MUST be set to 'latest'. It is currently set to ''',
>     last-rc-change='Thu May  7 11:37:58 2020', queued=0ms, exec=130ms
> * PostgreSQLService_stop_0 on node2 'invalid parameter' (2): call=65, status=complete, exitreason='Parameter "recovery_target_timeline" MUST be set to 'latest'. It is currently set to ''',
>     last-rc-change='Thu May  7 11:37:50 2020', queued=0ms, exec=127ms
> ```
> 
> View the value of the parameter.
> 
> ```
> postgres=# show recovery_target_timeline;
>  recovery_target_timeline 
> --------------------------
>  latest
> (1 row)
> ```
> 
> Thank you for your help！
Hello)

I have the same error, and I've enabled logs on postgresql12.
```
log_destination = 'stderr'
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%a.log'
log_file_mode = 0600
log_min_duration_statement = 30000
log_lock_waits = on
```

So I'm noticed next:
= When I try to start pgsql over pcs, I'got 
```
Failed Resource Actions:
  * pgsqld_stop_0 on pgsql-01 'invalid parameter' (2): call=254, status='complete', exitreason='Parameter "recovery_target_timeline" MUST be set to 'latest'. It is currently set to ''', last
-rc-change='2022-03-28 18:50:38 +05:00', queued=0ms, exec=94ms
```
+ I don't have any logs in /var/lib/pgsql/data/log/

= Otherwise when I start postgresql direct (I've got logs on /var/lib/pgsql/data/log/)

**Comment by tomjelinek** [comment]
You may have misconfigured your pgsql. That is not a pcs issue. I'm sorry we don't have much expertise with pgsql and we cannot provide further assistance. Please, post your question to [users@clusterlabs.org](mailto:users@clusterlabs.org) mailing list. The list is being read by a much broader audience including people who run pgsql in their clusters and are able to help you. Be sure to post the whole cluster configuration `pcs config` (or at least `pcs resource config pgsqld`) and status `pcs status`, it will make it easier to find out what's wrong.

**Comment by kyourselfer** [comment]
> 
Ok, I see) Anyway Thanks for your attention!
