### ISSUE TITLE
pcsd i18n

### ISSUE THREAD

**Issue by Jaycean** [ClusterLabs/pcs#254]
- The project does not support I18N, do you have this plan?

**Comment by tomjelinek** [comment]
This is not on the radar currently due to limited resources and other priorities. Also, we haven't got any requests for it until now as far as I remember. Do you have any specific issues or areas you would like to support i18n or are you looking for a complete i18n support throughout the whole project?

**Comment by Jaycean** [comment]
@tomjelinek Thank you for your answer
- My project needs to use Chinese. SUSE is a German company. If there is no I18N, how can the German version be achieved? So I think the project can meet the basic needs by supporting Chinese, German and English

**Comment by Jaycean** [comment]
- Because of the needs of the project, we have done a part of I18N work. If the project has a plan, we would also like to submit PR to improve i18 work with you

**Comment by tomjelinek** [comment]
There is no German version of pcs/pcsd. And SUSE is not involved in any way in the pcs/pcsd project. Are you actually interested about SUSE projects called hawk or crmshell?

**Comment by Jaycean** [comment]
We used PCSD and did part of the I18N work, so we want to ask the community if there is a plan so that we can submit PR and make some contributions. Hawk, we tried to compile but failed, and we are actively communicating with the community

**Comment by tomjelinek** [comment]
Currently, we have no plan to implement I18N support in pcs. We don't have bandwidth to do so and there are other tasks with higher priorities we must attend to.
However, if you submit a PR we will evaluate it and consider for inclusion.

**Comment by Jaycean** [comment]
Thank you for your patience. We will improve I18N and submit PR to the community
