### ISSUE TITLE
[Question]where to config res action parameters

### ISSUE THREAD

**Issue by liuxiran** [ClusterLabs/pcs#255]
HI all, I tried to use pcsd to create resource:
Provider：ocf:heartbeat
type: IPaddr2
but I could not  find where to config action params like: monitor interval.
so my question is if the pcsd support to config res action params? and where can I config them?

Thanks and expecting a reply～

**Comment by tomjelinek** [comment]
Hi,

Unfortunately, it is not possible to configure resource operations (including monitor interval) using the web UI. The only way to configure those with pcs is using command line commands `pcs resource create`, `pcs resource update` and `pcs resource op`.

**Comment by liuxiran** [comment]
Thanks for your reply，I will try to config it by command line.

By the way, do you have a plane to add more config to web UI, maybe it would be more convenience to config ha.

**Comment by tomjelinek** [comment]
There are plans to add more features to web UI, including resource operations configuration. It is rather a long term plan, though. We are currently in the process of implementing a brand new web UI. Due to suboptimal architecture of the current web UI, it is very difficult and resource demanding to add new features there.

**Comment by liuxiran** [comment]
Wow, this is really good news，but I have not found the new web UI branch in this repository, in `public` folder I have found this one: `https://github.com/idevat/pcs-web-ui`, so If this `pcs-web-ui` is the one  you are  currently in the process ?

**Comment by tomjelinek** [comment]
Yes, that's the new web UI.
