### ISSUE TITLE
Fencing history is displayed in crm_mon when quorum unblock is executed.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/pcs#257]
Hi All,

When creating a Pacemaker cluster with the pcs included in RHEL8.2, the fencing history of executing quorum unblock to start on a single node is displayed.

This seems to be because off fencing is being executed with the stonith_admin command in the execution of quorum unblock.

```
[root@hpdb0101 ~]# pcs quorum unblock --force
Node: hpdb0201 confirmed fenced
Quorum unblocked
Waiting for nodes canceled
[root@hpdb0101 ~]# crm_mon -rfA1m3
Cluster Summary:
  * Stack: corosync
  * Current DC: hpdb0101 (version 2.0.3-5.el8-4b1f869f0f) - partition with quorum
  * Last updated: Tue Sep  8 09:48:07 2020
  * Last change:  Tue Sep  8 09:48:04 2020 by root via cibadmin on hpdb0101
  * 2 nodes configured
  * 2 resource instances configured

Node List:
  * Online: [ hpdb0101 ]
  * OFFLINE: [ hpdb0201 ]

Full List of Resources:
  * Clone Set: ping-clone [ping]:
    * ping      (ocf::pacemaker:ping):  Starting hpdb0101
    * Stopped: [ hpdb0201 ]

Migration Summary:

Fencing History:
  * turning off of hpdb0201 successful: delegate=a human, client=stonith_admin.300925, origin=hpdb0101, completed='2020-09-08 09:48:04 +09:00'
```

The user hasn't actually seen fencing work off the node, but it's shown in the history.
This fencing history can be confusing to users.

If possible, why not clear this fencing history with stonith_admin -c after executing quorum unblock with pcs?

Best Regards,
Hideo Yamauchi.

**Comment by ondrejmular** [comment]
Calling `stonith_admin --history=<node-name> --cleanup` is not a good idea as it would clean whole fencing history for the affected nodes, including events not triggered by `pcs quorum unblock`.

Also you can clearly see that the action was triggered by an admin based on `delegate=a human`.

**Comment by HideoYamauchi** [comment]
Hi Ondrej,

Thanks for your comment.
We understand this specification.

I have closed this issue.

Many thanks,
Hideo Yamauchi.
