### ISSUE TITLE
PCS Issue with python

### ISSUE THREAD

**Issue by danner26** [ClusterLabs/pcs#258]
I am on CentOS 8 and have multiple instances of python installed. I have fully installed pcs and am able to authorize my cluster servers. The issue is when I try to make a new cluster:

```
[root@REDACTED ~]# /usr/bin/python3 /usr/sbin/pcs cluster setup REDACTED REDACTED.REDACTED.com REDACTED.REDACTED.com
No addresses specified for host 'REDACTED.REDACTED.com', using 'REDACTED.REDACTED.com'
No addresses specified for host 'REDACTED.REDACTED.com', using 'REDACTED.REDACTED.com'
Destroying cluster on hosts: 'REDACTED.REDACTED.com', 'REDACTED.REDACTED.com'...
Error: REDACTED.REDACTED.com: Error destroying cluster:
[]
["Traceback (most recent call last):\n", "  File \"/usr/sbin/pcs\", line 6, in <module>\n", "    from pkg_resources import load_entry_point\n", "ImportError: cannot import name 'load_entry_point'\n"]
1
REDACTED.REDACTED.com: Successfully destroyed cluster
Error: Errors have occurred, therefore pcs is unable to continue
```

Any idea what I may have wrong? I believe I have all of the dependencies installed.

**Comment by tomjelinek** [comment]
It looks like you are missing python-setuptools package.

Several pcs commands, including cluster setup, connect to pcsd on cluster nodes and pcsd then runs pcs on those nodes. Make sure python-setuptools is available there.

**Comment by danner26** [comment]
I ended up recreating my environments after waiting a few days. Thank you for the response but I was able to get everything working in CentOS 7. CentOS 8 did not have the lv2cluster package available. I will close this since I no longer can work on it. Thanks again
