### ISSUE TITLE
SBD_SYNC_RESOURCE_STARTUP is not taken into account when rewriting /etc/sysconfig/sbd

### ISSUE THREAD

**Issue by inouekazu** [ClusterLabs/pcs#267]
The ```pcs stonith sbd enable``` command in RHEL8.3 does not take into account the ```SBD_SYNC_RESOURCE_STARTUP``` parameter in ```/etc/sysconfig/sbd```.
Therefore, the ability to better control the synchronization between SBD and Pacemaker (*1) is not available.
Shouldn't the ```SBD_SYNC_RESOURCE_STARTUP``` setting be inherited when rewriting?

*1 https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.3_release_notes/new-features#BZ-1718324

```
# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.3 (Ootpa)

# rpm -q sbd pcs
sbd-1.4.1-7.el8.x86_64
pcs-0.10.6-4.el8.x86_64

(1) state before 'pcs stonith sbd enable'
# grep ^[A-Z] /etc/sysconfig/sbd
SBD_PACEMAKER=yes
SBD_STARTMODE=always
SBD_DELAY_START=no
SBD_WATCHDOG_DEV=/dev/watchdog
SBD_WATCHDOG_TIMEOUT=5
SBD_TIMEOUT_ACTION=flush,reboot
SBD_MOVE_TO_ROOT_CGROUP=auto
SBD_SYNC_RESOURCE_STARTUP=yes
SBD_OPTS=

# pcs cluster start --all
# grep "daemon.warning.*sbd" /var/log/messages
#

(2) state after 'pcs stonith sbd enable'
# pcs stonith sbd device setup device=/dev/vdb5
# pcs stonith sbd enable device=/dev/vdb5
Running SBD pre-enabling checks...
rhel83-1: SBD pre-enabling checks done
rhel83-2: SBD pre-enabling checks done
Distributing SBD config...
rhel83-1: SBD config saved
rhel83-2: SBD config saved
Enabling sbd...
rhel83-1: sbd enabled
rhel83-2: sbd enabled
Warning: Cluster restart is required in order to apply these changes.

# cat -n /etc/sysconfig/sbd
     1  # This file has been generated by pcs.
     2  SBD_DELAY_START=no
     3  SBD_DEVICE="/dev/vdb5"
     4  SBD_OPTS="-n rhel83-1"
     5  SBD_PACEMAKER=yes
     6  SBD_STARTMODE=always
     7  SBD_WATCHDOG_DEV=/dev/watchdog
     8  SBD_WATCHDOG_TIMEOUT=5

# pcs cluster start --all
# grep "daemon.warning.*sbd" /var/log/messages
Dec 16 13:11:03 rhel83-1 <daemon.warning> sbd[47642]: warning: main: SBD built against pacemaker supporting pacemakerd-API. Should think about enabling SBD_SYNC_RESOURCE_STARTUP.
```

**Comment by mirecheck** [comment]
Hello @inouekazu,

We are not going to address this issue because:
* pcs always rewrites whole sbd config, but this option can be set by pcs using `--force` option
* it is going to be fixed in sbd and pacemaker enabling this option by default

There are sbd [1] and pacemaker [2] BZs for RHEL which enable start-up
synchronization by default.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1873135
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1873138

**Comment by inouekazu** [comment]
> * it is going to be fixed in sbd and pacemaker enabling this option by default

I've confirmed that the default values are set in RHEL 8.4 Beta. Thank you.
