### ISSUE TITLE
webui error/bug 

### ISSUE THREAD

**Issue by Tsunani** [ClusterLabs/pcs#453]
Hello all. Can I ask for help in this direction?
My old Issue - https://github.com/ClusterLabs/PAF/issues/199

I think it's trouble in pcsd, but I can't prove.
Promotable clone in web send Warning "Resource is promotable but has not been promoted on any node".
And i find this warning in file - test_entity.rb.

`  def test_to_status_primitive_version2
    obj = ClusterEntity::Clone.new(
      @cib.elements["//clone[@id='stateful-promotable']"],
      @crm_mon,
      ClusterEntity::get_rsc_status(@crm_mon)
    )
    json ='{
      "id": "stateful-promotable",
      "meta_attr": [
        {
          "id": "stateful-promotable-meta_attributes-promotable",
          "name": "promotable",
          "value": "true"
        },
        {
          "id": "stateful-promotable-meta_attributes-a",
          "name": "a",
          "value": "1"
        },
        {
          "id": "stateful-promotable-meta_attributes-b",
          "name": "b",
          "value": "1"
        }
      ],
      "error_list": [],
      "warning_list": [
        {
          "message": "Resource is promotable but has not been promoted on any node.",
          "type": "no_master"
        }
      ],
      "class_type": "clone",
      "parent_id": null,
      "disabled": false,
      "status": "blocked",
      "promotable": true,
      "member": {
        "id": "promotable",
        "meta_attr": [
          {
            "id": "promotable-meta_attributes-a",
            "name": "a",
            "value": "0"
          },
          {
            "id": "promotable-meta_attributes-c",
            "name": "c",
            "value": "0"
          }
        ],
        "utilization": [],
        "error_list": [],
        "warning_list": [],
        "class_type": "primitive",
        "parent_id": "stateful-promotable",
        "disabled": false,
        "agentname": "ocf::pacemaker:Stateful",
        "provider": "pacemaker",
        "type": "Stateful",
        "stonith": false,
        "instance_attr": [],
        "status": "blocked",
        "class": "ocf",
        "crm_status": [
        ],
        "operations": []
      }
    }'
    hash = JSON.parse(json, {:symbolize_names => true})
    assert_equal(hash, obj.to_status('2'))
  end
end`

thanks

**Comment by tomjelinek** [comment]
Hi @Tsunani,

What is your pcs version?

**Comment by Tsunani** [comment]
@tomjelinek pcs-0.10.5

**Comment by tomjelinek** [comment]
@Tsunani In the original issue I can see your pacemaker version is 2.1.1. Is that correct? What is your OS and version?

**Comment by tomjelinek** [comment]
@Tsunani What is the output of `pacemakerd --features`?

**Comment by Tsunani** [comment]
@tomjelinek  Sorry for the long reply. 
`pacemakerd --features`
```
Pacemaker 2.1.1-alt1 (Build: 77db57872)
 Supporting v3.10.2: agent-manpages corosync-ge-2 generated-manpages ipmiservicelogd monotonic nagios ncurses profile remote servicelog systemd
```

**Comment by tomjelinek** [comment]
I see. Alt Linux 9 seems to be distributing pacemaker-2.1 and pcs-0.10. This version combination can work, but it requires pacemaker to be compiled with `--enable-compat-2.0`. This makes pacemaker preserve certain output as it was in 2.0, which is required for pcs-0.10 to work correctly. Since the output of `pacemakerd --features` is missing `compat-2.0`, the compatibility mode is not enabled.

This needs to be fixed in Alt Linux. They should either use `--enable-compat-2.0` when compiling pacemaker or upgrade pcs to 0.11 series.

I'll update pcs readme file to clarify this.

**Comment by Tsunani** [comment]
@tomjelinek Thank you for the answer. I will write additionally to Alt Linux bugzilla this massage.

**Comment by Tsunani** [comment]
In Ubuntu -
```
# cat /etc/*rele*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```
output of `pacemakerd --features`

```
Pacemaker 2.0.3 (Build: 4b1f869f0f)
 Supporting v3.2.1:  generated-manpages agent-manpages ascii-docs publican-docs ncurses libqb-logging libqb-ipc lha-fencing systemd nagios  corosync-native atomic-attrd acls
```

It must be so, right?

**Comment by tomjelinek** [comment]
Ubuntu 20.04 ships pcs 0.10 and pacemaker 2.0. That works fine.

**Comment by Tsunani** [comment]
Thank you, Issue i close.

**Comment by idevat** [comment]
Just for reference: readme updated in #454, #455

**Comment by Tsunani** [comment]
Sorry, i ask 1 question.
pacemakerd --features

Pacemaker 1.1.24 (Build 3850484742)
Supporting v3.0.14:  generated-manpages agent-manpages asclii-docs publican-docs ncurses libqb-logging libqb-ipc iha-fencing systemd nagios  corosync-native atomic-attrd snmp libesmtp acls

Is very old?

**Comment by Tsunani** [comment]
Thank you for your reply.
