### ISSUE TITLE
Server is fenced with "unknown error"

### ISSUE THREAD

**Issue by NanyinK** [ClusterLabs/pcs#471]
Hi Team,

Recently my servers reboot randomly due to the "fence". I checked and found there's no problem on the resources (CPU/Memory) or network connection.

Logs : 

> Feb 21 22:37:56 crmd[1828]:  notice: State transition S_IDLE -> S_POLICY_ENGINE
Feb 21 22:37:56 pengine[1827]: warning: Processing failed monitor of mode1:3 on node5.domian: unknown error
Feb 21 22:37:56 pengine[1827]: warning: Cluster node node5.domian will be fenced: mode1:3 failed there
Feb 21 22:37:57 pengine[1827]: warning: Scheduling Node node5.domian for STONITH
Feb 21 22:37:57 pengine[1827]:  notice: Stop of failed resource mode1:3 is implicit after node5.domian is fenced
Feb 21 22:37:57 pengine[1827]:  notice:  * Fence (reboot) node5.domian 'mode1:3 failed there'
Feb 21 22:37:57 pengine[1827]:  notice:  * Stop       dlm:3                 (                                node5.domian )   due to node availability
Feb 21 22:37:57 pengine[1827]:  notice:  * Stop       clvmd:3               (                                node5.domian )   due to node availability
Feb 21 22:37:57 pengine[1827]:  notice:  * Stop       mode1:3     (                                node5.domian )   due to node availability
Feb 21 22:37:57 pengine[1827]:  notice:  * Move       vmfence_instance01      (   node5.domian -> node1.domian )
Feb 21 22:37:57 pengine[1827]:  notice:  * Move       vmfence_instance02      (     node1.domian -> node2.domian )
Feb 21 22:37:57 pengine[1827]:  notice:  * Move       vmfence_instance03      (     node2.domian -> node3.domian )
Feb 21 22:37:57 pengine[1827]:  notice:  * Move       vmfence_instance04      (        node3.domian -> node4.domian )
Feb 21 22:37:57 pengine[1827]:  notice:  * Move       vmfence_instance05      (     node4.domian -> node6.domian )
Feb 21 22:37:57 pengine[1827]:  notice:  * Move       vmfence_instance06      (     node6.domian -> node7.domian )
Feb 21 22:37:57 pengine[1827]:  notice:  * Move       vmfence_instance07      (      node7.domian -> node8.domian )
Feb 21 22:37:57 pengine[1827]: warning: Calculated transition 52 (with warnings), saving inputs in /var/lib/pacemaker/pengine/pe-warn-43.bz2
Feb 21 22:37:57 pengine[1827]: warning: Processing failed monitor of mode1:3 on node5.domian: unknown error
Feb 21 22:37:57 pengine[1827]: warning: Cluster node node5.domian will be fenced: mode1:3 failed there
Feb 21 22:37:57 pengine[1827]: warning: Scheduling Node node5.domian for STONITH
Feb 21 22:37:57 pengine[1827]:  notice: Stop of failed resource mode1:3 is implicit after node5.domian is fenced
Feb 21 22:37:57 pengine[1827]:  notice:  * Fence (reboot) node5.domian 'mode1:3 failed there'
Feb 21 22:37:57 pengine[1827]:  notice:  * Stop       dlm:3                 (                                node5.domian )   due to node availability
Feb 21 22:37:57 pengine[1827]:  notice:  * Stop       clvmd:3               (                                node5.domian )   due to node availability
Feb 21 22:37:57 pengine[1827]:  notice:  * Stop       mode1:3     (                                node5.domian )   due to node availability
Feb 21 22:37:57 pengine[1827]:  notice:  * Move       vmfence_instance01      (   node5.domian -> node1.domian )
Feb 21 22:37:57 pengine[1827]:  notice:  * Move       vmfence_instance02      (     node1.domian -> node2.domian )
Feb 21 22:37:57 pengine[1827]:  notice:  * Move       vmfence_instance03      (     node2.domian -> node3.domian )
Feb 21 22:37:57 pengine[1827]:  notice:  * Move       vmfence_instance04      (        node3.domian -> node4.domian )
Feb 21 22:37:57 pengine[1827]:  notice:  * Move       vmfence_instance05      (     node4.domian -> node6.domian )
Feb 21 22:37:57 pengine[1827]:  notice:  * Move       vmfence_instance06      (     node6.domian -> node7.domian )
Feb 21 22:37:57 pengine[1827]:  notice:  * Move       vmfence_instance07      (      node7.domian -> node8.domian )
Feb 21 22:37:57 pengine[1827]: warning: Calculated transition 53 (with warnings), saving inputs in /var/lib/pacemaker/pengine/pe-warn-44.bz2
Feb 21 22:37:57 crmd[1828]:  notice: Initiating stop operation vmfence_instance02_stop_0 on node1.domian
Feb 21 22:37:57 crmd[1828]:  notice: Initiating stop operation vmfence_instance03_stop_0 on node2.domian
Feb 21 22:37:57 crmd[1828]:  notice: Initiating stop operation vmfence_instance04_stop_0 on node3.domian
Feb 21 22:37:57 crmd[1828]:  notice: Initiating stop operation vmfence_instance05_stop_0 on node4.domian
Feb 21 22:37:57 crmd[1828]:  notice: Initiating stop operation vmfence_instance06_stop_0 locally on node6.domian
Feb 21 22:37:57 crmd[1828]:  notice: Initiating stop operation vmfence_instance07_stop_0 on node7.domian
Feb 21 22:37:57 crmd[1828]:  notice: Requesting fencing (reboot) of node node5.domian
Feb 21 22:37:57 stonith-ng[1824]:  notice: Client crmd.1828.3cefd9b2 wants to fence (reboot) 'node5.domain' with device '(any)'

I can see something related to "due to node availability", but from our sight there is no network issue.

Also I can see  {Processing failed monitor of mode1:3 on node5.domian: unknown error}
It's talking about the monitor operation, but I dont know what it really is.

Could someone can identify the issue or give us some clues/advice? 
And what is the monitor operation? what does it do?

Thanks in advance.

**Comment by tomjelinek** [comment]
Hi @NanyinK,

Thanks for reaching out. Your issue, however, doesn't seem to be related to pcs itself. Pcs is merely a configuration / management tool, while cluster communication and resources placement is handled by corosync and pacemaker projects respectively.

Monitor operation is usually run periodically by pacemaker for all resources defined in a cluster. Its purpose is to detect whether resources are running on nodes where pacemaker expects them to be running and not on other nodes. Check [Pacemaker Explained](https://clusterlabs.org/pacemaker/doc/2.1/Pacemaker_Explained/html/resources.html#monitoring-resources-for-failure) for more info.

Based on the log, it looks like resource `mode1` failed on `node5.domian` which caused the cluster to fence the node. 

You can find additional help at ClusterLabs [users mailinglist](https://lists.clusterlabs.org/mailman/listinfo/users). If you decide to write there, attach your cluster configuration (CIB or output of `pcs configure`) as well, please.
