### ISSUE TITLE
improve robustness of gem check

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ClusterLabs/pcs#501]
If you have multiple versions of the same gem installed (for example json 2.5.1 and 2.6.1)
this will happen
```
checking ruby gem: json... yes (detected: 2.6.1, 2.3.0)
./configure: line 7805: 2.3.0: command not found
```

See https://bugs.gentoo.org/840478

**Comment by tomjelinek** [comment]
Thanks for reporting this issue!
