### ISSUE TITLE
How many nodes cluster supports

### ISSUE THREAD

**Issue by umardraz** [ClusterLabs/pcs#503]
Hi

I am running a 3 nodes cluster on my AWS vms where I have plan to use 3 nodes for my websites. Now the issue is only 2 nodes at a time mount the lvm not all the 3 nodes. Here is the error that I saw.

```

Cluster name: wp-cluster
Cluster Summary:
  * Stack: corosync
  * Current DC: g2fs-1 (version 2.1.2-4.el8-ada5c3b36e2) - partition with quorum
  * Last updated: Mon Apr 25 14:43:24 2022
  * Last change:  Sun Apr 24 18:15:21 2022 by hacluster via crmd on g2fs-2
  * 3 nodes configured
  * 13 resource instances configured

Node List:
  * Online: [ g2fs-1 g2fs-2 g2fs-3 ]

Full List of Resources:
  * Clone Set: locking-clone [locking]:
    * Started: [ g2fs-1 g2fs-2 g2fs-3 ]
  * Clone Set: shared_vg1-clone [shared_vg1]:
    * Started: [ g2fs-1 g2fs-3 ]
    * Stopped: [ g2fs-2 ]
  * wpfence	(stonith:fence_aws):	 Started g2fs-2

Failed Resource Actions:
  * sharedfs1_start_0 on g2fs-2 'error' (1): call=46, status='complete', exitreason='Couldn't mount device [/dev/shared_vg1/shared_lv1] as /mnt/webgfs', last-rc-change='Sun Apr 24 18:15:25 2022', queued=0ms, exec=741ms

Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled
[root@g2fs-2 ~]# 

```

Now if I just stop g2fs-1 or g2fs-3 then node g2fs-2 successfully mount the lvm volume, but if I again power on g2fs-3 then g2fs-3 will not mount lvm volume until I shutdown either g2fs-2 or g2fs-1.

So the question is that cluster only support 2 nodes at a time or I have not configured it properly?

**Comment by tomjelinek** [comment]
Hi,

It is definitely possible to run clusters with more than 2 nodes. The maximum count depends on your environment and Corosync configuration. Up to 16 nodes may run perfectly fine with no special configuration, with Corosync 3.x maybe even 32 nodes. And if that's not enough, you can scale even further with Pacemaker remote nodes.

This looks like a configuration issue to me. I recommend you asking at users@clusterlabs.org mailing list to reach broader audience and people who have experience with gfs2. Don't forget to attach cluster configuration and logs.

**Comment by umardraz** [comment]
Thanks

I will subscribe to this list and will post my question there
