### ISSUE TITLE
PCS 0.10.x support for Pacemaker 2.1.x

### ISSUE THREAD

**Issue by SomanathThilak** [ClusterLabs/pcs#504]
Hi ,

Due to a python version dependency i am planning to use pcs 0.10.x .

Now I would like to know if pcs 0.10.x can be used with Pacemaker 2.1.x

**Comment by tomjelinek** [comment]
Hi,

Thanks for reaching out. Yes, pcs 0.10.x can be used with Pacemaker 2.1.x, as long as Pacemaker is compiled with `--enable-compat-2.0` option.
