### ISSUE TITLE
web ui  password is not encrypted

### ISSUE THREAD

**Issue by XingWei-Liu** [ClusterLabs/pcs#553]
hi
when i use the pcs web ui ,i found some issue.
There is a plaintext password on the login interface.
![image](https://user-images.githubusercontent.com/56296184/187340289-8c3d2475-0339-4091-bb69-6403c74df0ff.png)

**Comment by idevat** [comment]
Communication between `pcsd` and brower is via `https`. So, the password is encrypted during this communication.

**Comment by XingWei-Liu** [comment]
but  password  can be search in  payload by use browser,  it seems not safe enough.

**Comment by XingWei-Liu** [comment]
> Communication between `pcsd` and brower is via `https`. So, the password is encrypted during this communication.

but password can be search in payload by use browser, it seems not safe enough.

**Comment by idevat** [comment]
@XingWei-Liu, what kind of attack are you worried about?

**Comment by XingWei-Liu** [comment]
> 

i just think  it may can use python to get payload  info which password is not encrypted

**Comment by idevat** [comment]
@XingWei-Liu I'm not sure if I understand it correctly. Can you elaborate it a bit?

**Comment by XingWei-Liu** [comment]
Just an idea, not actually encountered.
For example, when the user enters the user password on the web interface and clicks to log in, if there is a program intercepting the payload data of the HA interface at this time, won't the password be leaked?

**Comment by idevat** [comment]
Outside your machine is communication encrypted via SSL.

The encryption does not protect anything if your machine is is attacked by someone who can break somehow into your browser and read your communications inside it. Since the attacker already knows what login request to sent to pcsd. For attacker, the encrypted credentials is enough to get access to pcsd and obtain session id.

**Comment by XingWei-Liu** [comment]
understand ， thanks for your answer
