### ISSUE TITLE
How to fix the issue for "you really should enable notify when using this RA " when the resource was created.

### ISSUE THREAD

**Issue by tuninger** [ClusterLabs/pcs#656]
Cluster name: mycluster
Status of pacemakerd: 'Pacemaker is running' (last updated 2023-03-13 19:56:23 +08:00)
Cluster Summary:
  * Stack: corosync
  * Current DC: server-1 (version 2.1.5-a3f44794f94) - partition with quorum
  * Last updated: Mon Mar 13 19:56:23 2023
  * Last change:  Mon Mar 13 19:56:15 2023 by root via cibadmin on server-1
  * 2 nodes configured
  * 1 resource instance configured

Node List:
  * Online: [ server-1 server-2 ]

Full List of Resources:
  * clusterdata (ocf:linbit:drbd):       Stopped

Failed Resource Actions:
  * clusterdata start on server-1 returned 'not configured' (you really should enable notify when using this RA (or set ignore_missing_notifications=true)) at Mon Mar 13 19:56:15 2023 after 53ms

Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled

**Comment by tomjelinek** [comment]
Based on the error message, this looks like an issue or rather a miscofiguration of the DRBD agent. According to DRBD documentation, the agent must be run as a promotable clone with notifications enabled. To fix your configuration, run `pcs resource promotable clusterdata notify=true`.

Please, bear in mind, that pcs team don't develop DRBD and therefore we don't offer support and help for it. If you have any issues with DRBD, it's better to contact DRBD support or users@clusterlabs.org mailing list. Thank you.
