### ISSUE TITLE
when make rpm,an ambiguous error has occurred,it seems to be related to gawk?

### ISSUE THREAD

**Issue by ashore1992** [ClusterLabs/pcs#695]
pcs version is v0.10.14.All steps were './autogen.sh && ./configure && make rpm'.Attachment for detailed error.
[pcs-error.txt](https://github.com/ClusterLabs/pcs/files/11752163/pcs-error.txt)

**Comment by tomjelinek** [comment]
Hi @ashore1992,

It looks like your gawk doesn't support the `-i` option. Can you let us know what OS and gawk version are you running?

**Comment by ashore1992** [comment]
> Hi @ashore1992,
> 
> It looks like your gawk doesn't support the `-i` option. Can you let us know what OS and gawk version are you running?

arch is mips64.
gawk version is 4.0.2,is the version old?

**Comment by tomjelinek** [comment]
> gawk version is 4.0.2,is the version old?

That's rather old. You need at least gawk 4.1.0 released in 2013: https://lwn.net/Articles/550212/

**Comment by ashore1992** [comment]
> > gawk version is 4.0.2,is the version old?
> 
> That's rather old. You need at least gawk 4.1.0 released in 2013: https://lwn.net/Articles/550212/

Thanks!,it succeed,I have updated gawk to 4.1.0,the error disappeard.But new error came,could you help me?

rpmbuild --define "_sourcedir /mnt/pcs/rpm" --define "_specdir /mnt/pcs/rpm" --define "_builddir /mnt/pcs/rpm" --define "_srcrpmdir /mnt/pcs/rpm" --define "_rpmdir /mnt/pcs/rpm" -ba rpm/pcs.spec
错误：行 150：未知标签：Recommends: liberation-sans-fonts
make: *** [rpm] 错误 1

**Comment by tomjelinek** [comment]
continuing in #703
