### ISSUE TITLE
Question : Specifications of pcs resource move.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/pcs#697]
Hi All,

We have confirmed the behavior of pcs resource move on RHEL9.1.
The version of pcs is 0.11.3.

When moving resources with pcs resource move, the INFINITY constraint for the move is automatically removed if the move succeeds.

However, if the move fails, the INFININITY constraint for the move remains.

Just to be sure, I also checked with RHEL9.2 pcs, but the same behavior was obtained.

Is it by design that the INFINITY constraint remains if the move fails?
We expected the constraint to be removed eventually, whether the move succeeded or failed.

Is there any information discussed about this spec somewhere?
Or is it possible to specify the pcs execution option and delete the constraint even if the move fails?

(For example, if it is a specification, it may be effective to issue an error message that the constraint must be deleted by eliminating the cause if the move fails because the constraint remains.)

Best Regards,
Hideo Yamauchi.

**Comment by ondrejmular** [comment]
Hi, thank you for bringing up this question.

The behavior you described is expected and documented in the pcs documentation. According to the pcs man page for the `pcs resource move` command:

```The constraint needed for moving the resource will be automatically removed once the resource is running on its new location. The command will fail in case it is not possible to verify that the resource will not be moved back after deleting the constraint.```

Although it is not explicitly mentioned, the removal of the location constraint occurs only while the `resource move` command is running. If the command fails, the constraint will not be removed. The `pcs resource move` command typically fails when pcs is unable to verify that the resource will not be relocated after the constraint is removed.

Currently, there is no direct way to force the `pcs resource move` command to remove the constraint regardless of its effect on the affected resource. However, you can achieve this by using the following command:

`export resource=<resource id>; export node=<node name>; pcs resource move $resource $node || pcs resource clear $resource $node`

We can improve the resource move documentation and enhance the error message when pcs decides not to remove the constraint. It would be helpful to suggest a command in the error message that can be used to manually remove the constraint.

**Comment by HideoYamauchi** [comment]
Hi Ondrej,

Thanks for the comment and the command line example.
I understood that by design the user should run a pcs resource clear in case of failure.

I will talk with Japanese community members based on your answers.
Also, it would be nice if the manual and error messages could be improved so as not to confuse users.

Many thanks,
Hideo Yamauchi.

**Comment by ondrejmular** [comment]
I filed a bugzilla to address this issue:
https://bugzilla.redhat.com/show_bug.cgi?id=2219554

And I created another bugzilla to improve `pcs resource clear` command and make it safe for this kind of use cases:
https://bugzilla.redhat.com/show_bug.cgi?id=2219555

**Comment by HideoYamauchi** [comment]
Hi Ondrej,

Okay!

Thanks,
Hideo Yamauchi.

**Comment by tomjelinek** [comment]
Error messages and documentation have been improved in #737 and #738

**Comment by HideoYamauchi** [comment]
Hi Tomas,

Okay!

Best Regards,
Hideo Yamauchi.
