### ISSUE TITLE
[cli]: refuse to trigger a direct configuration change when "-f <tmpcib>" is provided spuriously

### ISSUE THREAD

**Issue by jnpkrn** [ClusterLabs/pcs#75]
Also, documentation/help screen could mark such "spurious use" contexts explicitly.

**Comment by jnpkrn** [comment]
What's also missing is a notion that `-f <filename>` doesn't serve solely
for output, but may denote the input in rare cases (`pcs config export ...`).

**Comment by tomjelinek** [comment]
Starting with version 0.10, pcs exits with an error when `-f` flag is used with a command that does not support it.

**Comment by tomjelinek** [comment]
The documentation has been improved as recommended: https://github.com/ClusterLabs/pcs/commit/a5b6dcdaeda0dbe678e03f8618a17c72fa8dc382
