### ISSUE TITLE
Error: Agent 'ocf:precona:mysql_prm_gtid' is not installed or does not provide valid metadata: crm_resource: Metadata query for ocf:precona:mysql_prm_gtid failed

### ISSUE THREAD

**Issue by infa-rammekal** [ClusterLabs/pcs#753]
I need help to fix this issue.

Trying to execute the below command, I installed Percona resource agents already. Below agent is available under /usr/lib/ocf/resource.d/percona

```
# pcs resource create p_mysql ocf:precona:mysql_prm_gtid \
  config="/etc/my.cnf" binary=/usr/sbin/mysqld \
  user="mysql" group="mysql" log="/var/log/mysql/mysqld.log" \
  pid="/var/lib/mysql/mysqld.pid" socket="/var/lib/mysql/mysqld.sock" \
  replication_user="repl" replication_passwd="xxxx" max_slave_lag="1000" \
  test_user="pacemaker" test_passwd="xxxx" \
  op start timeout="600s" op stop timeout="600s" \
  op promote timeout="600s" op demote timeout="600s" \
  op monitor role="Master" timeout="30s" interval="60s" OCF_CHECK_LEVEL="10" \
  op monitor role="Slave" timeout="30s" interval="90s" OCF_CHECK_LEVEL="10" \
  op monitor interval="10s"
```
Error: Agent 'ocf:precona:mysql_prm_gtid' is not installed or does not provide valid metadata: crm_resource: Metadata query for ocf:precona:mysql_prm_gtid failed: No such device or address, Error performing operation: No such object, use --force to override

**Comment by infa-rammekal** [comment]
BTW - this is on ubuntu 22 on AWS ec2

**Comment by tomjelinek** [comment]
Are the agents called percona or precona? You talk about the former, but run the pcs command with the latter.

**Comment by infa-rammekal** [comment]
thank you. it was my typo.
    On Monday, October 9, 2023 at 04:15:28 AM PDT, Tomáš Jelínek ***@***.***> wrote:  
 
 


Are the agents called percona or precona? You talk about the former, but run the pcs command with the latter.
