### ISSUE TITLE
More options to configure.

### ISSUE THREAD

**Issue by q53** [ClusterLabs/pcs#77]
Hello everybody.
Version pcs 0.9.143.on SL7
We need a capability to bind on particular IPs. But there is no such option except direct edit of ssl.rb, what is a bad way because it will be overridden after first update.
Why even such things are hardcoded?

**Comment by tomjelinek** [comment]
Hello,
It is now possible to configure which IP addresses pcsd will bind to in pcsd config file (`/etc/sysconfig/pcsd`, `/etc/default/pcsd` on Debian). Here is the patch: https://github.com/feist/pcs/commit/81a952d8a6db4bba0408fc4d874e4e3c90a68286
