### ISSUE TITLE
pcs cluster uidgid allows the gid field to be optional but corosync fails to start when the gid field is blank

### ISSUE THREAD

**Issue by pjwiseman** [ClusterLabs/pcs#772]
The pcs cluster uidgid add command takes an optional uid and gid. However the permission file writes a blank gid. Due to changes on [2017-11-06](https://github.com/corosync/corosync/commit/f05d1c9293133c398bd06a16b9fc7bfbfb2a21e8) corosync then fails to start.

See https://github.com/corosync/corosync/issues/741.  The new corosync "failing to start" behaviour is expected when gid is blank.

Possible options
1. pcs cluster uidgid add - change to mandatory uid and gid
2. pcs cluster uidgid add - write a uid permission only, rather than a blank gid (needs testing with corosync)

```
$ sudo pcs cluster uidgid add

Usage: pcs cluster uidgid...
    uidgid
        List the current configured uids and gids of users allowed to connect
        to corosync.

    uidgid add [uid=<uid>] [gid=<gid>]
```

```
$ cat pcs-uidgid-54324- 
uidgid {
  uid: 54324
gid: 
}
```

```
$ /usr/sbin/corosync -f
parser error: /etc/corosync/uidgid.d/pcs-uidgid-54324-:3: The '' group is not found in /etc/group, please read the documentation.
```

**Comment by mirecheck** [comment]
@pjwiseman, thank you for reporting this issue.
