### ISSUE TITLE
PCS Failing to Install with RUBY 3.1.2 (Dependency issue)

### ISSUE THREAD

**Issue by ncsrikar** [ClusterLabs/pcs#785]
PCS RPM that comes in the Alma Linux 9.3 Repository which is of the version PCS 0.11.6 does not seem to install with Ruby Version greater than Ruby 3.0

<img width="1702" alt="image" src="https://github.com/ClusterLabs/pcs/assets/28345602/4645d794-0c0f-4b63-8156-6feea6a07651">

Assuming something wrong with the RPM I attempted to the build my own PCS version and faced the same issue again, 
I have Ruby 3.1.2 installed and I have tried this a couple of times! 
```
[root@myMachine /]# cd /home/user/pcs/
[root@myMachine pcs]# ./config
bash: ./config: No such file or directory
[root@SSM-On-Prem pcs]# ./configure
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for gawk... (cached) gawk
checking for pkg-config... /bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for a Python interpreter with version >= 3.9... python3
checking for python3... /bin/python3
checking for python3 version... 3.9
checking for python3 platform... linux
checking for python3 script directory... ${prefix}/lib/python3.9/site-packages
checking for python3 extension module directory... ${exec_prefix}/lib64/python3.9/site-packages
checking for systemd... yes
checking for pkg-conf systemd var systemdsystemunitdir... yes (detected: /usr/lib/systemd/system)
checking for pkg-conf systemd var systemdsystemunitpath... yes (detected: /etc/systemd/system:/etc/systemd/system:/run/systemd/system:/usr/local/lib/systemd/system:/usr/lib/systemd/system:/usr/lib/systemd/system:/lib/systemd/system)
checking for ruby... /bin/ruby
checking for ruby... no
configure: error: Package requirements ( >= 2.5) were not met:

Package '>=', required by 'virtual:world', not found
Package '2.5', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ruby_CFLAGS
and ruby_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by mirecheck** [comment]
Hi @ncsrikar,
ad 1) installation
It looks like you have enabled some ruby modules which has non-default ruby version. Check `dnf module list`. Pcs is built against default ruby version (3.0.* something).

ad 2) build pcs from sources
You doesn't have installed package ruby-devel. Install it and try again.

**Comment by ncsrikar** [comment]
Hi @mirecheck, 
I installed Ruby from the official Alma linux repository and this is the latest version they seem to have. 

<img width="816" alt="image" src="https://github.com/ClusterLabs/pcs/assets/28345602/399911d3-3a5e-40b4-a84f-c9a7ae56ab16">

pcs claims support for above Ruby >=2.5....so I found it was odd not installing for Ruby 3.1...
I checked the libraries installed and there is libruby.so.3.1() and libruby.so.3.1.2() available in my system.

**Comment by mirecheck** [comment]
Hi @ncsrikar,
it is true that upstream pcs supports Ruby >= 2.5. The issue on Alma linux is that pcs bundles some rubygems which has extensions written in C language and they were compiled against ruby and ruby libraries of version 3.0.

You can try:
1. remove ruby-3.1 packages and then install pcs which should work
2. re-build your own pcs package against ruby-3.1
3. ask Alma linux support to provide pcs package built against ruby dependencies of desired version
