### ISSUE TITLE
[Question] For what pcsd is used?

### ISSUE THREAD

**Issue by bayram-dev** [ClusterLabs/pcs#809]
Does it used to sync  corosync configuration between nodes? Didn't find this particular information on doc, but on [other wesbite](https://www.cjcheema.com/2018/09/04/simple-way-to-configure-ngnix-high-availability-with-pacemaker-and-corosync-on-centos7/#:~:text=The%20pcsd%20daemon%20works%20with,service%20on%20other%20cluster%20nodes).

If not - how does this conf file syncronization works?
if so - does it mean that failed pscd daemon causes issue with syncing configuratons between nodes or it can be also smth else?

**Comment by mirecheck** [comment]
Hi @bayram-dev,
pcsd is used for communication between nodes over HTTP protocol. It executes
tasks locally or ask remote daemons to do some work or get information. It also
provides web-ui if enabled.

Yes, it does syncrhonize `corosync.conf` configuration file. It is synchronized
during execution of commands which manipulate with `corosync.conf`. For example
`pcs cluster setup` command or `pcs cluster config update` command or
other commands for adding/removing cluster nodes.

If a `corosync.conf` file is edited manually and not via pcs commands than it
needs to be synchronized manually. There is command `pcs cluster sync` which
synchronize `corosync.conf` to all cluster nodes found in the current
`corosync.conf` file. Depending on the changed configuration, `corosync.conf` needs
to be reload or sometimes whole cluster needs to be restarted.

If pcsd daemon is failed or not running then synchronization will not work and
also most of the pcs commands.
