### ISSUE TITLE
Question : About the use of the STONITH module of glue in pcs.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/pcs#81]
Hi All,

We installed pcsd0.9.148 on RHEL7.2.
In addition, we install glue component.
 * http://hg.linux-ha.org/glue/

Is the external module included in glue available as STONITH module in pcs?
In addition, how becomes the command-line of create when we use glue?

Best Regards,
Hideo Yamauchi.

**Comment by tomjelinek** [comment]
Hi Hideo,

If the external module implements the same interface as fence agents from https://github.com/ClusterLabs/fence-agents project then it should work.

Hope that helps.

**Comment by HideoYamauchi** [comment]
Hi Tomas,

Furthermore, let me confirm it.

glue is installed in the next directory.
[root@rh72-01 ~]# ls /usr/lib64/stonith/plugins/external/
drac5  dracmc-telnet  hetzner  hmchttp  ibmrsa  ibmrsa-telnet  ipmi  ippower9258  kdumpcheck  libvirt  nut  rackpdu  riloe  ssh  vcenter  vmware  xen0  xen0-ha

The list command does not display a module of glue, is this a specification?

[root@rh72-01 ~]# pcs stonith list
fence_alom - Fence agent for Sun ALOM
fence_amt - Fence agent for AMT
(snip)
fence_zvmip - Fence agent for use with z/VM Virtual Machines

The create command does not make STONITH with a module of glue when I do not appoint force option.
Is this a specification, too?

[root@rh72-01 ~]# pcs stonith create test external/ssh  params pcmk_reboot_timeout=300 pcmk_reboot_retries=1 hostlist="rh72-02"
Error: Unable to create resource 'stonith:external/ssh', it is not installed on this system (use --force to override)



[root@rh72-01 ~]# pcs stonith create test external/ssh  params pcmk_reboot_timeout=300 pcmk_reboot_retries=1 hostlist="rh72-02" --force

[root@rh72-01 ~]# pcs status
Cluster name: cluster1
Last updated: Thu Feb 25 08:08:29 2016          Last change: Thu Feb 25 08:07:50 2016 by root via cibadmin on rh72-01
Stack: corosync
Current DC: rh72-02 (version 1.1.14-70404b0) - partition with quorum
2 nodes and 1 resource configured

Online: [ rh72-01 rh72-02 ]

Full list of resources:

 test   (stonith:external/ssh): Started rh72-01

PCSD Status:
  rh72-01: Online
  rh72-02: Online

Daemon Status:
  corosync: active/disabled
  pacemaker: active/disabled
  pcsd: active/disabled

Best Regards,
Hideo Yamauchi.

**Comment by tomjelinek** [comment]
Hi Hideo,

I am sorry, pcs does not support external STONITH agents currently. We may take a look at this in future.

Best Regards,
Tomas

**Comment by HideoYamauchi** [comment]
Hi Tomas,

Okay!

We do not use the STONITH module of glue in pcs.
We wait for future support of pcs.

Many thanks,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Because a discussion was over, this is closed.

**Comment by tomjelinek** [comment]
Reopening the issue so we can track the request for adding external stonith agents support to pcs.

**Comment by HideoYamauchi** [comment]
Hi Tomas,

Sorry...
Okay!

Best Regards,
Hideo Yamauchi.

**Comment by moonracer** [comment]
Hi,
I am glad I found this issue, although not glad that the issue itself exists ;)
I am currently building a Dual Primary setup on CentOS 7.2 with pcs where I need to use external agent for STONITH (external/hetzner).
Since pcs doesn't support external STONITH agents a Dual Primary Setup is not an option anymore.
I would be really great to have an option of using external STONITH agents in pcs.
Or do you see an other option to realize STONITH and not using external/hetzner?
Best Regards,
Marek

**Comment by tomjelinek** [comment]
Hi @moonracer,

You can try creating your STONITH resources in pcs with `--force` flag. Since pcs is merely a configuration tool and pacemaker is the one doing the heavy lifting here, it might work for you.

Best Regards,
Tomas

**Comment by tomjelinek** [comment]
Hi @HideoYamauchi and @moonracer,

I just pushed a commit https://github.com/ClusterLabs/pcs/commit/491ac087fd06480a9fda0dfc5dd97f6b9dfbae56 which overhauls pretty much all code dealing with resource and stonith agents. With this patch pcs gets all information about the agents from pacemaker. This means pcs now supports the same set of agents as pacemaker does, including external and cluster-glue agents.

Best Regards,
Tomas

**Comment by HideoYamauchi** [comment]
Hi Tomas,

Great!!
I confirm your correction.

Many thanks!
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Tomas,

Even if stonith module of glue did not appoint "force" option, I confirmed that I could set pcs command.

```
[root@rh72-01-pcsd ~]# pcs stonith create stonith1  external/ssh params pcmk_reboot_timeout=300 pcmk_reboot_retries=1 hostlist="rh72-01"

[root@rh72-01-pcsd ~]# pcs status
Cluster name: test
WARNING: corosync and pacemaker node names do not match (IPs used in setup?)
Stack: corosync
Current DC: rh72-01-pcsd (version 1.1.15-e174ec8) - partition with quorum
Last updated: Wed Oct 12 11:19:57 2016          Last change: Wed Oct 12 11:19:46 2016 by root via cibadmin on rh72-01-pcsd

1 node and 2 resources configured

Online: [ rh72-01-pcsd ]

Full list of resources:

 test   (ocf::heartbeat:Dummy): Started rh72-01-pcsd
 stonith1       (stonith:external/ssh): Started rh72-01-pcsd

(snip)
```


Best Regards,
Hideo Yaamuchi.

**Comment by tomjelinek** [comment]
Hi Hideo,

Thank you for testing this in such a short time!

I'm closing this issue because it has been successfully resolved.

**Comment by HideoYamauchi** [comment]
thanks!
