### ISSUE TITLE
pcs cluster disable/start/stop should accept a --corosync-only and --pacemaker-only parameter

### ISSUE THREAD

**Issue by roidelapluie** [ClusterLabs/pcs#87]
It would be useful to be able to only stop pacemaker or corosync with the pcs cluster disable/start/stop commands

**Comment by tomjelinek** [comment]
Why do you think this would be useful, what is your use case?

**Comment by roidelapluie** [comment]
Well you could just stop pacemaker and continue to have corosync quorum information up.

**Comment by tomjelinek** [comment]
Well, yes. But for what purpose?

**Comment by ChristianCiach** [comment]
It feels wrong to install pacemaker on an arbitrator-only node. Also, corosync is A LOT more telorant regarding different corosync versions inside the cluster. But an outdated pacemaker installation on the arbitrator f***s the whole cluster up majorly, as I just experienced again.

**Comment by tomjelinek** [comment]
@ChristianCiach
I do not get what you are asking about. If an arbitrator-only node is not a part of any cluster, it does not matter what pacemaker version is installed there. If such arbitrator node is a part of a cluster, why install pacemaker version different than what other nodes in the cluster have in the first place?

**Comment by ChristianCiach** [comment]
> why install pacemaker version different than what other nodes in the cluster have in the first place?

Exactly this was the issue. The arbitrator node has just been "forgotten" to be updated. Yes, this was a human error, but as pacemaker is not necessary on an arbitrator-only node, I would prefer to not install pacemaker at all on this node, just to minimize the chance of those possible issues.

Also, pacemaker checks for the existance of the OCF scripts, even when this node is set to "standby". It feels dirty to install pacemaker + our custom OCF scripts just for pcs to work.

**Comment by lyon667** [comment]
@ChristianCiach: You must NOT run pacemaker as a cluster node on arbitrator! It is only installed as a dependency for PCS but you should not be starting it at all. The whole point of an arbitrator is it has to be independent from any cluster.

**Comment by ChristianCiach** [comment]
But wouldn't pacemaker be started by pcs when doing a "pcs cluster start"?

**Comment by lyon667** [comment]
@ChristianCiach: It wouldn't as long as there's not cluster defined on arbitrator. If your arbitrator is installed on a cluster node, you should either remove the node from cluster or use another machine.

**Comment by ChristianCiach** [comment]
I don't really get what you are saying. AFAIK, the arbitrator would become part as the cluster as soon as I configure corosync through pcs. Maybe I am wrong on this part. I will investigate this. Maybe it would be better for me to not install pcs on the arbitrator at all, but than I would need to configure corosync manually on this node.

**Comment by lyon667** [comment]
@ChristianCiach: Just to be sure, are we talking about booth arbitrator, right?

**Comment by ChristianCiach** [comment]
Ne, we are not :) We are using corosync as the arbitrator.

**Comment by lyon667** [comment]
@ChristianCiach: Ah, confusion of terms then. You cannot actually use a third node like that without running full corosync+pacemaker stack. You either need to keep the third node as a full cluster node or take a look at corosync-qdevice which does exactly what you wanted (you'll need to use pcs-0.9.158 or higher).

**Comment by ChristianCiach** [comment]
@lyon667  Awesome! I didn't know I could use corosync-qdevice without a full corosync installation! This seems promising!

Actually, I may even use Booth instead. When we created the cluster around 3 to 4 years ago, Booth was at version 0.1.0 or 0.2.0. That wasn't really trustworthy and I wasn't even able to get it working. Maybe I will give it another shot. Thanks for your help this far!
