### ISSUE TITLE
Add default action meta-data in resource describe.

### ISSUE THREAD

**Issue by sathlan** [ClusterLabs/pcs#90]
Hi,

The describe command show all the parameters given by the ocf resource agent, but the action block.

It would be useful to get the default actions value as well in this commands, so that one knows what they are easily.  Everything seems in place to add it with the `utils.get_default_op_values(ra_type)` function.

My problem here is in the rewrite of the puppet-pacemaker provider, it's required to have access to the default values to check if the current values have been modified or not.  The only way to do it would be to reimplement `get_default_op_values`.  As I believe it might be useful information for others as well, It make more sense to add it to the `pcs resource description` command.

**Comment by tomjelinek** [comment]
Hi,

fixed in https://github.com/ClusterLabs/pcs/commit/4428fa4e9880c9b9834669f5046cc49cd7a28244. Pcs now displays default resource operations in the `pcs resource describe`  command.
