### ISSUE TITLE
RFE: have pcs status work with local CIB files via -f

### ISSUE THREAD

**Issue by mbaldessari** [ClusterLabs/pcs#93]
I'd love to be able to do the following on a cib.xml.live collected by crm_report.
$ ~/Devel/pcs/pcs/pcs -f cib.xml.live status
Error: Unable to connect to localhost ([Errno 111] Connection refused)

Not sure if it is a valid use case, but it would be a nice to have. Feel free to close if not doable/not
interesting ;)

**Comment by tomjelinek** [comment]
Hi Michele,

I suppose your machine doesn't run pcsd and isn't actually part of a cluster. Is that right?

**Comment by mbaldessari** [comment]
Hi Tomas,

correct. The use case being that I get some cib.xml.live from a customer and want to see a quick status
via pcs on my laptop (which is not part of any cluster). Not sure how much we care about such a use case, but I thought I'd throw it out there ;)

**Comment by tomjelinek** [comment]
Then this is a known issue and we plan to fix it. Let's leave this open to track progress.

**Comment by tomjelinek** [comment]
This issue has been fixed by https://github.com/ClusterLabs/pcs/commit/8696f5e4f072ac88a3e20b1b376ea8de823f7aa7
