### ISSUE TITLE
pcs certificate verify failed 

### ISSUE THREAD

**Issue by salehabbas** [ClusterLabs/pcs#94]
Hi,

Information about the system:
- pcs-0.9.139-9 from base centos repo
- Amazon Linux AMI release 2016.03 

I have been working on starting a cluster of two nodes and when I ran the following command:
`cs cluster auth node1 node2`

I could see the following in pcsd's log file:

`ERROR OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=SSLv3 read client certificate A: tlsv1 alert unknown ca
    /usr/share/ruby/2.0/openssl/ssl.rb:280:in accept
[2016-05-07 14:03:29] ERROR OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=SSLv3 read client certificate A: tlsv1 alert unknown ca
    /usr/share/ruby/2.0/openssl/ssl.rb:280:in accept`

I do not know why the verification happens. I thought as the following option had been sent in the pcs ssl file, that should not happen: 
`:SSLVerifyClient    => OpenSSL::SSL::VERIFY_NONE,`

Thanks

**Comment by kzinas** [comment]
Have you found solution for this issue? Because I encoutered the same on RHEL7.4 / Redhat Gluster storage 3.3   encoutred the same. they are   using old pcs version pcs-0.9.137-13.el7_1.2.x86_64.

**Comment by tomjelinek** [comment]
Both pcs 0.9.137 and pcs 0.9.139 are very old. There have been several changes related to SSL and network communication in the meantime. I was able to reproduce the issue using pcs 0.9.137. However, recent pcs versions work just fine for me.

**Comment by kzinas** [comment]
Thanks, looks this was issue with RHGS  distribution channel packaging, all you need add you need to add RHEL HA channel to you distros and you`ll get pcs 0.9.58 .

/Domantas
