### ISSUE TITLE
Bundler error while building PCSD

### ISSUE THREAD

**Issue by anuphalarnkar** [ClusterLabs/pcs#99]
**OS**: RHEL 7.2
**Arch**: PPC64LE
**uname -a :** Linux xxxxxxxxx 3.10.0-229.ael7b.ppc64le #1 SMP Fri Jan 30 12:03:50 EST 2015 ppc64le ppc64le ppc64le GNU/Linux

**Versions of installed ruby packages:**
libruby2_1-2_1.ppc64le         2.1.3-4.1               
ruby.ppc64le                          2.0.0.598-25.el7_1      
ruby-irb.noarch                      2.0.0.598-25.el7_1      
ruby-libs.ppc64le                   2.0.0.598-25.el7_1      
rubygem-bigdecimal.ppc64le 1.2.0-25.el7_1        
rubygem-bundler.noarch        1.7.8-3.el7             
rubygem-io-console.ppc64le  0.4.2-25.el7_1     
rubygem-json.ppc64le            1.7.7-25.el7_1         
rubygem-net-http-persistent.noarch
rubygem-psych.ppc64le         2.0.0-25.el7_1          
rubygem-rdoc.noarch             4.0.0-25.el7_1         
rubygem-thor.noarch              0.19.1-1.el7           
rubygems.noarch                    2.0.14-25.el7_1        

After successful build of **PCS**, I followed instructions on **README** to build **PCSD**. But, I got below error.

//******************************************************************************************************************
**$** make get_gems
bundle package
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
Rubygems 2.0.14 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Using backports 3.6.8
Installing eventmachine 1.2.0.1 with native extensions

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

Gem files will remain installed in /home/anuph/.gem/ruby/gems/eventmachine-1.2.0.1 for inspection.
Results logged to /home/anuph/.gem/ruby/gems/eventmachine-1.2.0.1/ext/gem_make.out
Installing json 1.8.3 with native extensions

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

Gem files will remain installed in /home/anuph/.gem/ruby/gems/json-1.8.3 for inspection.
Results logged to /home/anuph/.gem/ruby/gems/json-1.8.3/ext/json/ext/generator/gem_make.out
Using multi_json 1.12.0
Using open4 1.3.4
Using orderedhash 0.0.6
Using rack 1.6.4
Installing rpam-ruby19 1.2.1 with native extensions

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

Gem files will remain installed in /home/anuph/.gem/ruby/gems/rpam-ruby19-1.2.1 for inspection.
Results logged to /home/anuph/.gem/ruby/gems/rpam-ruby19-1.2.1/ext/Rpam/gem_make.out
Using tilt 2.0.3
Using bundler 1.12.5
An error occurred while installing eventmachine (1.2.0.1), and Bundler cannot continue.
Make sure that `gem install eventmachine -v '1.2.0.1'` succeeds before bundling.
make: *** [get_gems] Error 5

//*********************************************************************************************************************
I feel this error could be related to mismatch in ruby/gem versions. Not sure though. 
Will appreciate any inputs on  above.

Thanks and Regards,
Anup Halarnkar

**Comment by tomjelinek** [comment]
Do you have ruby development files installed? It's `ruby-devel` package in RHEL. I'm not sure why mkmf.rb looks for it in `/usr/share/include/`, though. For me it works with `/usr/include/ruby.h`.

**Comment by jnpkrn** [comment]
See also the other reply:
http://oss.clusterlabs.org/pipermail/developers/2016-June/000235.html

@anuphalarnkar: Next time, please be more transparent and do not address several venues separately, as it leads to multiplied effort to answer your concerns.

**Comment by anuphalarnkar** [comment]
@tomjelinek Thanks a lot!!. Yes. ruby-devel solved the issue. But, somehow I was not getting it in yum search. Then, I had to enable an optional repo after which I got it.
@jnpkrn Sorry for posting it twice. On some forums, It takes days to get a reply. So, I had forwarded to both links. Apologize once again!!
Thanks again!! :)
